declarations.d.ts, definitions/commands-service.d.ts, definitions/commands.d.ts, dispatchers.ts, services/commands-service.ts
* Remove hardcoded commands
* Remove getPropSchemaAction
* Add completionData to ICommand interface - This way each command can specify data that will be used for autocompletion. For example build command can specify platforms("android", "ios", "wp8"),
plugin command can specify available plugin names, prop command can specify available property names i etc.
This is helper PR for this story http://teampulse.telerik.com/view#item/280276
=> Improve autocompletion

dispatchers.ts, helpers.ts, options.ts
Add some shorthands for help command: -h, ?, /?. Fix usage of shorthands, so when you specify -v for example to really use verbose mode.
http://teampulse.telerik.com/view#item/284030
=> Add shorthands for help command

dispatchers.ts
Add toString() call before calling toLowerCase() to make sure the value is a string. This prevents exception when passed value is a number.
Fixes http://teampulse.telerik.com/view#item/284099
=> Fix exception in getCommandName

declarations.d.ts, errors.ts
Add failWithoutHelp method to Errors. It should be used when you want to break the execution without printing help.
=> Add fail without printing help

commands/post-install.ts, host-info.ts, mobile/android/android-device.ts, mobile/android/android-emulator-services.ts, mobile/ios/ios-emulator-services.ts, mobile/mobile-core/device-discovery.ts, mobile/wp8/wp8-emulator-services.ts
If user cannot use 7zip, he is unable to create projects, unable to build etc. So on post-install we check if we are able to execute the 7za file and if ENOENT is return we show the user where he can find system requirements.
Fix host-info paths in some files and remove host-info reference from some other files.
http://teampulse.telerik.com/view#item/285027
=> Add check if 7za can be executed

errors.ts
1. we should not fail in the catch clause, because that would stop further executing of this function, and the program would exit with the wrong exit code
2. We cannot use this.$xxx resolve, because this is a free-standing function. The old code would throw.
=> Convert js callstack to ts

mobile/android/android-emulator-services.ts
When you specify --geny option of $ appbuilder emulate android command, we check for genyshell in the PATH environment variable. As on MacOS genyshell and the real program that we need for genymotion (player) are in different directories, we fail with incorrect message.
Fixes http://teampulse.telerik.com/view#item/285302
=> Fix genymotion check

mobile/android/android-emulator-services.ts
If Genymotion is not configured properly, the error message is not correct. Using correct constant.
=> Fix incorrect message for genymotion

definitions/lodash.d.ts, helpers.ts
Update Lodash definitions to allow chaining of .values method. Add createTable helper method which creates cli-table from passed headers and data.
Fixes are required for this issue: http://teampulse.telerik.com/view#item/285533
=> Update Lodash definitions, createTable helper

static-config-base.ts
The default value doesn't allow us to use constructions like public get START_PACKAGE_ACTIVITY_NAME(): string { ... } in each CLI's. We need such construction in appbuilder-cli to support different start package activity names, based on the project type.
=> Remove default value for START_PACKAGE_ACTIVITY

file-system.ts
Pull request https://github.com/telerik/mobile-cli-lib/pull/187 changed the default behavior of the unzip method.
=> Code refactor to fix the bug introduced with PR #187

mobile/mobile-core/device-discovery.ts
Make sure iosDeviceDiscovery will not make commands fail on Linux. On Linux we MUST use IOSDeviceDiscoveryStub as we cannot execute iosDevice related commands.
=> Fix usage on Linux

mobile/mobile-core/device-discovery.ts
When you do not have connected devices and you execute $appbuilder device on Linux, we print:
null
Cannot find connected ...
Remove printing of error in case there's no error.
=> Do not show "null" message on Linux

mobile/ios/ios-device.ts
The code inside it calls this.$errors.fail and expects the program execution to stop.
Due to our implementation, the catch will prevent this from working and the program will continue executing in a bad state.
=> Remove bad try-catch

commands/post-install.ts
The package.tgz contains proper unix file attributes so we do not need to explicitly set them any more.
=> Remove unneeded chmod on user's machine on package install

logger.ts
Note: This shade of red is a lot different than the shade of red displayed by $errors.fail
Tested in cmd and bash under windows
=> Change $logger.error color to red

mobile/android/android-emulator-services.ts
Use lodash's startsWith method as the extension method startsWith (it was part of extensions.ts) had been removed.
=> Fix starting of genymotion emulator

file-system.ts
Under node 0.12 we generate invalid command line on Windows.
Needed to fix http://teampulse.telerik.com/view#item/285421
=> Fix unzipping on node 0.12

bootstrap.ts, commands/help.ts, declarations.d.ts, definitions/yok.d.ts, services/commands-service.ts, services/dynamic-help-service.ts, services/micro-templating-service.ts, yok.ts
Add support for multilevel hierarchical commands. This way we can use commands like $ appbuilder appmanager upload android declared as "appmanager|upload|android".
Add support for passing multiple arguments to dynamic calls, by changing regular expressions.
Add DynamicHelpService which is used to check different conditions when printing our help.
Use _.isBoolean where possible. Add dynamicHelpProvider which should be implemented by each CLI.
Use lodash _.template as it uses microTemplate internally and pass the help through it. This way we can write javascript directly in our help.txt.
Replace of all entries in the help content (when executing), which match our dynamicCallRegex with this.$injector.dynamicCall($1).wait()
This way you can call dynamic methods, by just using:
\<%= …
=> Support multilevel hierarchical commands

bootstrap.ts, commands/device/list-devices.ts, yok.ts
Fix code which should execute default hierarchical command which accepts arguments.
Split device commands in order to use different context for each of them,
=> Fix hierarchical commands

declarations.d.ts, services/analytics-service.ts
Add isEnabled method which returns true only when analytics tracking is enabled. We need the value in order to pass it to simulator in appbuilder-cli.
http://teampulse.telerik.com/view#item/286925
=> Add method to check if analytics tracking is enabled

bootstrap.ts, commands/device/list-devices.ts, commands/device/run-application.ts, commands/post-install.ts, declarations.d.ts, definitions/config.d.ts, definitions/mobile.d.ts, helpers.ts, http-client.ts, mobile/android/android-device.ts, mobile/android/android-emulator-services.ts, mobile/device-platforms-constants.ts, mobile/ios/ios-device.ts, mobile/ios/ios-emulator-services.ts, mobile/mobile-core/device-discovery.ts, mobile/mobile-core/devices-services.ts, mobile/mobile-helper.ts, mobile/wp8/wp8-emulator-services.ts, services/analytics-service.ts, services/auto-completion-service.ts, services/commands-service.ts, static-config-base.ts
Common lib is used by several CLIs - appbuilder-cli, nativescript-cli, etc. 
- There are several places where appbuilder is used, while it should be staticConfig.CLIENT_NAME. Fix all of these.
- Replace MobileHelper's exported functions in a new class - MobileHelper. This way we can resolve it from injector and it can easily use staticConfig's CLIENT_NAME. 
- Remove DevicePlatforms enum and add DevicePlatformsConstants class which can be used instead of the enum. 
- Add SYS_REQUIREMENTS_LINK to StaticConfig in order to have different links for each CLI. 
- Add getClientName and getPrivacyPolicyLink methods to IAnalyticsSettingsService.
http://teampulse.telerik.com/view#item/287728
=> Replace  appbuilder strings with CLIENT_NAME

mobile/mobile-helper.ts
In case the CLI doesn't support a mobile platform, for example WP8, but it is valid mobile platform according to normalizePlatformName(WP8 for example), we should break the execution.
=> Fix validation of device platform names

config-base.ts, definitions/config.d.ts, http-client.ts
Rename the following config options:
- FIDDLER_HOSTNAME to PROXY_HOSTNAME
- PROXY_TO_FIDDLER to USE_PROXY
Add PROXY_PORT option to config with default value 8888. Add ConfigBase class which should be used as a base for CLI specific configs.
Required for https://github.com/NativeScript/nativescript-cli/issues/297 and https://github.com/NativeScript/nativescript-cli/issues/302
=> Enable proxy using for http requests

config-base.ts
ConfigBase must implement Config.IConfig, not IConfiguration. IConfiguration is specific for each CLI.
=> Fix ConfigBase parent

errors.ts, options.ts
Yargs adds -- options to yargs.argv in two ways (--profile-dir is added as profile-dir and profileDir). In order to workaround this behavior, we had to add  all dashed options in both ways to our known options. Fix our validation logic, so we'll have to add only profile-dir.
Remove check for client name when validating -- options. This way options will be validated no matter if CLIENT_NAME( tns) or CLIENT_NAME_ALIAS (nativescript) is used on command line.
=> Remove duplicate -- options

options.ts
Get back the availableDevices option that had been removed by mistake.
=> Get back availableDevices option

bootstrap.ts, commands/completion-prompt.ts, commands/post-install.ts
Implements https://github.com/NativeScript/nativescript-cli/issues/350
=> At post-install, ask the user to turn on command line autocompletion

bootstrap.ts, commands/help.ts, commands/post-install.ts, declarations.d.ts, definitions/config.d.ts, definitions/lodash.d.ts, definitions/marked.d.ts, file-system.ts, mobile/constants.ts, services/commands-service.ts, services/dynamic-help-service.ts, services/html-help-service.ts, services/micro-templating-service.ts, static-config-base.ts, yok.ts
CLIs should be able to show HTML help when using ```<cli name> help <command name>```
When using ```<cli name> <command name> --help``` console help should be shown.
When an error is raised in command, only console help is shown.
* ```HelpCommand``` is modified to show console help when ```options.help``` is specified and html help when it is not.
* Add ```HtmlHelpService``` which handles both console and html help by parsing markdown help files.
* Each commands help is placed in a separate file. The files are markdown and they are used for both html and console help.
* Html pages are generated from markdown on post-install. As post-install command could fail before generating html pages, when html help should be shown, we check if command name is valid and if the command exists, but its …
=> Show HTML Help

services/analytics-service.ts
Currently analytics prompt is showing:
"Do you want to help us improve Telerik AppBuilderNaN You can read our official Privacy Policy at"
Instead it must show: "Do you want to help us improve Telerik AppBuilder by automatically sending anonymous usage statistics? We will not use this information to identify or contact you. You can read our official Privacy Policy at..."
The problem is with __two consecutive + signs__ used when message is generated.
=> Fix analytics prompt

services/html-help-service.ts
Remove the hack when parsing markdown text that has to be show on the console. The problem was with code in table, but it had been fixed in version 1.3.0 of marked-terminal.
Part of http://teampulse.telerik.com/view#item/259417
=> Fix marked-terminal parsing

commands/completion-prompt.ts, commands/post-install.ts, declarations.d.ts, sysinfo.ts
- Changed the prompt for enabling auto completion to proper English
- Changed warnings: only the first line is colored, the text is expanded, there are platform-specific hints
- Stop searching for java, instead search for android
=> Improve warnings and prompts at install

definitions/mobile.d.ts, mobile/ios/ios-proxy-services.ts
http://teampulse.telerik.com/view#item/287903
Post notification logic has been changed. With current implementation we try to receive all data from socket before sending the data is started. And this is ok on `OSX` but on `Windows` `receive` function is blocking and livesync command is not able to complete.
I've introduced two functions - one for debugger purposes and one that only sends the notification.
=> Fix livesync

bootstrap.ts, commands/preuninstall.ts, services/cancellation.ts
Add dev-preuninstall command which is used to execute preuninstall actions. It should be referenced from each CLI in its preuninstall script. Fix KillSwitches dir to be under our profile-dir directory.
=> Fix installation and uninstall of CLI

dispatchers.ts, services/html-help-service.ts
When you write `$ appbuilder` or `$ tns` we automatically open index.html in your default html editor. Change this behavior to show index.md in the console (full list of commands). The behavior now is:
`$ <cli_name>` - shows full list of commands in the console
`$ <cli_name> help` - shows full list of commands in the browser
`$ <cli_name> -h` - same as `$ <cli_name>` - shows full list of commands in the console
`$ <cli_name> help -h` - shows help for "help" command in the console
`$ <cli_name> help help` - shows help for "help" command in the browser
=> Fix console help when arguments are not passed

errors.ts
In case you are using Node 0.12.x and in config.json "debug" is set to true, the real error message is not printed to the output. When we are in debug mode, we print only the callstack and in Node 0.10.x , when fibers throw exception, the top row of the callstack is the error message. With Node 0.12.x, when error is thrown from fibers, the message is not part of the callstack for some reason. Workaround this behavior by checking the callstack and add the message in case it is missing.
=> Fix errors print in debug

mobile/android/android-emulator-services.ts
See https://github.com/NativeScript/nativescript-cli/issues/175
=> Support Google API images in Android Emulator.

services/commands-service.ts
"Returns - An array containing the DELETED element" - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice. 
We need to remove the element and are not interested in deleted element :smile_cat:
=> Fix commands parameters validation

declarations.d.ts, prompter.ts
In most cases one only needs to prompt the user for a single input.
I exposed a getString method similar to getPassword for facilitation.
promptForChoice on the other hand asks the user to choose from a list of options.
=> Add getString method to the prompter

definitions/logger.d.ts
Allow logger functions to be called without parameters
=> Fix ILogger definitions

helpers.ts
Used to remove elements from an array.
Contrary to `_.remove` removes only one element matching the predicate (if not explicitly specified otherwise)
=> Add generic remove function to helpers

services/cancellation.ts
Move KillSwitches dir to os.temp directory as when CLI is installed with sudo, we need correct privileges.
Fixes http://teampulse.telerik.com/view#item/289467
Fixes http://teampulse.telerik.com/view#item/289469
and possibly other sudo issues.
=> Move KillSwitches dir to tmp

services/auto-completion-service.ts
In some very old releases we were writing autocompletion information in ~/.profile. Remove this obsolete code, but do not write new autocompletion logic to this file as we do not want to do this anymore.
Fixes http://teampulse.telerik.com/view#item/289758
=> Remove obsolete autocompletion from .profile

services/html-help-service.ts
Links in markdown files should be stripped in console help. Fix the incorrect regex, so now the correct text between [ and ] will be shown.
Fixes: http://teampulse.telerik.com/view#item/290105
=> Fix markdown links in console

yok.ts
If hierarchical command does NOT have default command, for example `appbuilder build`, trying to execute it should print console help. Instead this leads to opening html help.
Set option.help to true in this case. Require the options in the action itself in order to prevent cyclic errors when yok and options are required.
Fixes http://teampulse.telerik.com/view#item/290168
=> Show command line help for hierarchical commands

definitions/options-service.d.ts, services/commands-service.ts
Use correct `_.startsWith` method, the used one was throwing exception. Move the logic for showing `-- options` to be at the beginning of the method, so you can write `$ appbuilder --` and to see all available options. Add logic to show shortcut options. Remove IOptionsService interface as the OptionsService was required for our old logic. Now, when external options are extending knownOpts of common lib's options, we do not need this service.
Fixes http://teampulse.telerik.com/view#item/288643
=> Fix tabtab logging

services/auto-completion-service.ts
When npm is installed with sudo, the installation command '$ sudo npm i -g appbuilder' fails to allow autocompletion as npm starts it with "nobody" user in some cases. Improve the error message in this case and show the real error only in debug mode.
Improves http://teampulse.telerik.com/view#item/288567
=> Improve message on autocomplete fail

definitions/mobile.d.ts, mobile/android/android-device.ts, mobile/android/android-emulator-services.ts, mobile/android/logcat-helper.ts, mobile/ios/ios-core.ts, mobile/ios/ios-emulator-services.ts, mobile/ios/ios-proxy-services.ts, options.ts
Until now the application output was printed only if the --printAppOutput option was specified. This PR changes this behavior and the application output is printed by default. The new option - justlaunch is introduced and if it is specified the application output is not printed. 
Also this PR removes the filtration of android logcat for projects created with nativescript-cli.
=> Show application output by default

services/commands-service.ts
This prevents "swallowing" of arguments, due to Array.splice()
See http://teampulse.telerik.com/view#item/290977
=> Fix command line validation logic

declarations.d.ts, services/typescript-compilation-service.ts
CLI has its own typescript definition files, which are used when we build typescript projects. Make sure to exclude them in case the project directory already has files with such name. This is the scenario with NativeScript TypeScript projects, which have android17.d.ts files in the templates and we are adding them again on build.
Fixes http://teampulse.telerik.com/view#item/290964
=> Prevent doubling of typescript definitions

definitions/commands.d.ts, definitions/config.d.ts, services/commands-service.ts
Introduce ON_PREM configuration setting
Introduce ICommand.isEnabled property with semantics:
- when explicitly false, do not execute command
- when true or undefined, execute it
See http://teampulse.telerik.com/view#item/288143
=> Introduce ON_PREM configuration setting

services/commands-service.ts
This prevents "swallowing" of arguments, due to Array.splice()
See http://teampulse.telerik.com/view#item/290977
=> Cherrypick more commits for ns 1.0.1 release

declarations.d.ts, yok.ts
In addition declare ErrorCodes enum as const
to conform with TypeScript 1.5
Fixes http://teampulse.telerik.com/view#item/291385
=> Fix hierarchical commands' case-sensitivity

commands/preuninstall.ts, services/cancellation.ts
Due to different security models on Windows and *ix, this code cannot be made to work reliably on all OSes. Because it exists only because Windows keeps executable code locked, the right thing to do is to execute it only on Windows.
=> Use Cancellation service only on Windows

commands/preuninstall.ts, services/auto-completion-service.ts
When you do not specify -g flag, we could still enable autocompletion, but currently this process fails as we are executing globally installed CLI (for example tns completion >> ...). Use the javascript from bin directory instead.
Fix dev-preuninstall command, which was failing due to incorrect service called in it (cancellationService is not called at all, so I removed it. In fact we have $cancellation, not $cancellationService).
=> Enable command autocompletion when local installation is used

services/auto-completion-service.ts
Linux has case-sensitive file system and autocompletion is unable to find correct appbuilder.js/nativescript.js file as it is searching for AppBuilder.js/NativeScript.js
=> Fix autocompletion on Linux

services/cancellation.ts
=> If none of these environmental variables exist; this will crash.  

mobile/ios/ios-device.ts
Whenever `USBMuxConnectByPort` fails to connect to a port on a device, either because the device is no longer there, or the connection is refused, it returns a negative value file descriptor. This upsets Node's `net.Socket` constructor that accepts a file descriptor and causes an assertion failure.
This patch handles bad file descriptors by creating a pristine `net.Socket` and emitting the `error` event on it.
=> Handle bad file descriptors in iOSDevice.connectToPort

services/cancellation.ts
Currently when you try to use CLI in more than one terminal simultaneously, only the last process keeps working, while the other ones stop immediately when the next process starts. This is due to our code, which recreates the "cli" watch file. Add check if the file exists and do not recreate it in such case.
Fixes http://teampulse.telerik.com/view#item/292941
=> Allow parallel executions of many CLIs

bootstrap.ts, commands/doctor.ts, commands/post-install.ts
See https://github.com/NativeScript/nativescript-cli/issues/480
=> Implement "doctor" command

options.ts
Yargs creates objects for options passed with dots, for example --var.debug.a 2 will create the object
```JavaScript
{
"debug": 2
}
```
Add the Object type as available for our options and replace failWithoutHelp with fail as the message says "Check the help below", but there's no help when `failWithoutHelp` is used.
Part of http://teampulse.telerik.com/view#item/292387
=> Add Object type to Options

declarations.d.ts, services/analytics-service.ts
When feature tracking is enabled, we need an easy way to track new features that will go in separate section on the feature page. Add such track method. When you want to track new information, just pass the feature name and its value to track method.
=> Add general track method

declarations.d.ts, options.ts, services/analytics-service.ts
Feature tracking is checking incorrect option - client.  As this option has different meaning in our CLIs, add new option - analyticsClient and use it instead of client when tracking features.
=> Fix analytics feature tracking

options.ts
This is the [right way](https://www.npmjs.com/package/yargs#options-key-opt) to use the `.options()` function of yargs.
=> Chain options before getting argv

services/html-help-service.ts
Fix the regex for markdown links, so `[\*\*](http://....)` can be shown correctly as \*\*
=> Fix markdown links in the console

declarations.d.ts, definitions/commands.d.ts, definitions/yargs.d.ts, options.ts, services/commands-service.ts
Each command can use specific dashed options (`-- avd <name>` for example is valid for one command, but not for other). Add dashedOptions parameter to ICommand interface and make sure to use it for validation when it exists. In case there's no dashedOptions paramter, use the common options.
Use correct types for yargs - "string", "boolean", etc. instead of 0, 1, 2 which were the result of our enum. Replace the enum with class and remove code, which we do not need anymore as yargs is doing its work as expected.
After yargs is updated to latest version, some fixes have to be applied - now when `yargs.options(opts).argv` is passed, it returns all members of `opts`, but the ones that are not part of process.argv have value undefined.
=> Add dashedOptions for each command

definitions/config.d.ts, dispatchers.ts, static-config-base.ts
In case the package.json has buildVersion property, concatenate it with the version from staticConfig and show it to user when `$ appbuilder --version` is invoked.
Add PATH_TO_PACKAGE_JSON to staticConfig in order to allow each CLI to specify where is its package.json.
=> Use package.json's buildVersion property

bootstrap.ts, commands/analytics.ts, commands/help.ts, declarations.d.ts, definitions/config.d.ts, services/analytics-service.ts, services/commands-service.ts, static-config-base.ts
Add error-reporting command that should be used in a similar manner as feature-usage-tracking command. The difference is that during installation, the exceptions tracking will be enabled without prompt (keep current behavior that we are tracking exceptions). It can be disabled later by using `$ appbuilder error-reporting disable`.
Refactor analytics-service in order to "hide" some methods from the interface and to simplify adding of new analytics commands and variables. 
**Rename feature-usage-tracking to usage-reporting**
=> Error-reporting command

commands/analytics.ts, commands/help.ts, declarations.d.ts, services/analytics-service.ts, services/commands-service.ts
- Fix behavior that is trying to login the user when tracking command - in fact we should first check if the user is logged in and if not, do not try to login.
- Make sure commands are tracked, but for some of them we should not ask the user for confirmation of usage reporting (for example help command). So add new command property - `disableAnalyticsConsentCheck` and set it to true for help, usage-reporting and error-reporting commands. Make sure to prevent commandsService for checking the consent when this property is true.
=> Fix analytics issues

mobile/android/android-device.ts
fixes https://github.com/NativeScript/nativescript-cli/issues/632
=> Allow the user to manually set Chrome app name

prompter.ts
When the console is not interactive there's no point in using the prompter at all.
Part of [#297090](http://teampulse.telerik.com/view#item/297090)'s implementation.
=> Fail in prompter when console is not interactive

dispatchers.ts
When package.json is changed from On premise scripts, it is encoded with BOM, so requiring it is failing with error. Use our readJson implementation which is able to read such file without errors.
=> Read package.json encoded with BOM

dispatchers.ts, options.ts
Yargs will parse all non-hyphenated values as strings in case we tell we want this. So, let's declare we want this and remove our hack, that's doing it. This will also fix the case when numbers like 8.0 are passed on the console. Yargs is giving them to us as "8", but we need the full value. With this fix, we'll receive "8.0".
=> Parse command line values as strings

yok.ts
In case command does not have default command and arguments are not passed, we are trying to execute default command, which is not expected. Make sure not to return true in this method, when there's no default command.
=> Do not call default command when there's no default command

mobile/android/android-emulator-services.ts, mobile/mobile-core/device-discovery.ts
In case user does not have Android SDK installed, we are trying to execute adb from CLI resources. This fails in case `$ <CLI> device` command or `$ <CLI> deploy <platform>` is executed as the "exec" cannot resolve the path with spaces.
Also fix the check dependencies of AndroidEmulatorService in order to fail with correct error message when something is not configured properly (currently it is failing with ENOENT error).
Fixes http://teampulse.telerik.com/view#item/297604
=> Fix adb spawn when path contains spaces

commands/device/stop-application.ts, mobile/ios/ios-core.ts
If you connect two iOS devices and execute `tns livesync` the following exception is thrown: 
`Multiple exceptions were thrown:
Command failed: /bin/sh -c node ~/Work/nativescript-cli/bin/nativescript.js device stop org.nativescript.debuggerApp iOS`
=> Don't fail when more than one ios devices are attached

mobile/android/android-emulator-services.ts, mobile/mobile-core/device-discovery.ts
When CLI is installed in directory, which has space (or the path above this dir has spaces) and android-sdk is not installed, we are trying to execute adb from our resources. This is failing due to missing `"` in our commands.
Fixes https://github.com/NativeScript/nativescript-cli/issues/470
=> Fix adb related commands when path has spaces

.gitignore, Gruntfile.js, bin/common-lib.js
Fix `grunt clean` task in order to remove only .js and .js.map files from common lib. Un-gitignore bin/common-lib.js file.
Fix rename package to work only when there's specific build number.
=> Fix grunt tasks

mobile/ios/ios-emulator-services.ts
Fix livesync to work with iOS 7.x
Fixes https://github.com/NativeScript/nativescript-cli/issues/761 and https://github.com/NativeScript/nativescript-cli/issues/762
=> Fix application glitches on iOS simulator after livesync

.npmignore, package.json
Set correct version of ios-sim-portable. Move typescript to devDependencies as it is not required for end users of common lib. Also npmignore some files.
=> Improve packing of common lib

errors.ts
Write errors to stderr instead of stdout, so cli's will work as proper command line tools.
=> Write error to stderr

bootstrap.ts, declarations.d.ts, definitions/config.d.ts, file-system.ts, package.json, resource-loader.ts, services/commands-service.ts, static-config-base.ts
Using the **command-help.json** file located inside the resources folder of any CLI client a tip can be shown after specific commands to help guide the user into successfully creating a project
=> Add workflows for screenbuilder commands

sysinfo.ts
Modified regex to extract java version for openjdk java version because
it has different format for showing version information than oracle
java.
For e.g. in case of __openjdk__
```
java -version
```
=> Adds handling for version extraction in case of openjdk

declarations.d.ts, services/commands-service.ts
Introduce non-mandatory ```disableCommandHelpSuggestion``` parameter for disabling suggestions upon successful execution of a command.
=> Introduce a way to disable command help suggestion

commands/help.ts, definitions/logger.d.ts, logger.ts, services/commands-service.ts, services/html-help-service.ts
This logic is used when printing help on the console, as well as for command suggestions.
=> Introduce $logger.printMarkdown

services/usb-livesync-service-base.ts
Move platform preparation out of `beforeBatchLiveSyncAction` and call it once
before processing changed files.
The actual preparation override submitted in a separate PR for `nativescript-cli`. I'd be happy to add/update tests for that logic, so feel free to point me in the right direction.
=> Don't prepare platform N times if N files have been changed.

sysinfo.ts
Fix NativeScript/nativescript-cli#936. Regex to read javac version was not working for openjdk java
version because it was expecting the output to starts with javac.
output with openjdk is:
```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
javac 1.8.0_45-internal
```
=> Fixes the javac version extraction issue

mobile/ios/ios-emulator-services.ts, services/usb-livesync-service-base.ts
1. We are now batching files and restarting just once.
2. No longer failing to restart the app after killing it since it hasn't already died by the time we try to start it.
I also pulled the batching/timeout code to a `SyncBatch` class, so we can share it with the android batch sync operation. Tested and working on an android emulator as well.
=> Livesync iOS simulator restart fixes

declarations.d.ts, sysinfo.ts
Ant had been used in older versions of NativeScript CLI. We do not use it
anymore, so remove the antVersion check.
=> Remove check for ant version

yok.ts
When you have class A in file A and class B in file B, that extends class A and you register both classes in the injector, trying to resolve the child (B) is leading to unexpected behavior. The constructor of B is called with arguments that are applicable to the base class (A). The reason is that the "extend" method is copying all properties from base class to the child. This includes the $inject property of the base class, so the annotate of the child class is not executed.
Fix this by checking both $inject property and the name of the function.
=> Fix resolving of child when parent is registered

mobile/android/android-application-manager.ts
If livesync android --watch command is executed and the application is not deployed on device, {N} deploys the app on every change. This happens because the installed applications are cached and actually the new application never appears in installed applications.
Fixes https://github.com/NativeScript/nativescript-cli/issues/977
=> Don't cache installed applications

services/auto-completion-service.ts
When user installs nativescript-cli with sudo (`sudo npm i -g nativescript`), npm uses `nobody` user for installation.
This user cannot update .bash_profile, .bashrc and .zshrc files as it has limited permissions.
Show correct message to the user when this happens. In some cases the error is EACCES, in other - EPERM.
=> Show message when sudo cannot update profiles

errors.ts
When `--log trace` or `--log debug` is used, we should print call stack of failure.
=> Print call stack when log trace/debug is used

definitions/mobile.d.ts, mobile/ios/ios-emulator-services.ts, mobile/wp8/wp8-emulator-services.ts
If `tns emulate ios` command is executed, `undefined is not a function` error is thrown
=> Fix tns emulate ios

declarations.d.ts, prompter.ts
If all schemas have default actions just execute them instead of throwing.
If any schema does not however have a default action throw.
=> Improve prompter behavior in interactive console

test/unit-tests/yok.ts, yok.ts
In case you have command called 'prop|print' and you want to add subcommand to it,
the injector will not try to resolve it. For example 'prop|print|myprop' will be resolved
as command 'prop|print' with argument 'myprop'.
Fix this by executing the full `_.each` and adjust the real parameters based on the last matching one.
=> Allow defining subcommands of subcommands

declarations.d.ts
Used whenever there's a problem with any of our resources - templates, json files etc
=> Introduce RESOURCE_PROBLEM error code

services/usb-livesync-service-base.ts
The check for modified files being excluded from livesync wasn't working.
Fixed by using the same code from the initial sync.
=> Fix livesync file watch exclusion check.

declarations.d.ts, file-system.ts
Add renameIfExists method to fs. Used to skip ENOENT errors when rename is called directly. Renames specified file to the specified name only in case it exists.
Returns True in case of successful rename. False in case the file does not exist.
=> Add renameIfExists method to fs

README.md, definitions/mobile.d.ts, mobile/android/logcat-helper.ts, package.json
When we print device logs, we execute `adb -s <device identifier> logcat`.
In case the device is not unlocked, we receive `undefined` for deviceIdentifier and the command leaks adb processes.
It looks like executing `adb -s <invalid id> logcat` is not closed even after our process exits.
Fix this by checking the passed value. Also change the return type of `LogcatHelper`'s `start` method to void
as noone is using the returned child_process.
=> Fix leaking of adb processes

commands/device/list-devices.ts, mobile/mobile-core/ios-device-discovery.ts
Instead of directly trying to execute ios device-related commands, first check for an error in iTunes.
If an error is present cache it and do not execute anything anymore.
If no error is present try and execute command but do NOT cache. Next command execution attempt will trigger a new check to make sure everything's still all right
Includes minor fix for not showing CLI table when no appropriate devices attached
Ping @Fatme @rosen-vladimirov
=> Do NOT execute ios device commands if iTunes error present

mobile/android/logcat-helper.ts, static-config-base.ts, sysinfo.ts
Also add quotes around path to adb, so even when the path contains spaces, the command will be executed without troubles.
Fix checking for javac version to use JAVA_HOME in case it is defined.
=> Fix printing of adb logcat

definitions/logger.d.ts, logger.ts, test/unit-tests/stubs.ts
Would be used for issuing warnings with a [WARNING] label. This way relevant warnings can easily be recognized when parsing a CLI client's output
Ping @rosen-vladimirov @Fatme @teobugslayer
=> Introduce warnWithLabel method in logger

verify-node-version.ts
There are some node versions that cannot be used with our CLIs.
In case user is trying to use CLI with them, inform him that it is not supported and exit the process.
=> Fail in case node version is blacklisted

commands/device/list-devices.ts, mobile/android/android-device.ts
In order to get information about Android devices, CLI's calling `adb shell cat /system/build.prop` and parsing the result.
For new emulators and devices, the file does not contain all information that we need.
We can get it by using `adb shell getprop`. As I'm not sure if this command will work on all devices, I've try-catched the code and call the old code for backwards compatibility.
Fix the regex that parses the result to work with both commands.
Also fix bug in list devices command that pushes undefined to cli-table and causes exception there. Pass empty strings instead.
=> Improve getting device info for Android

mobile/android/android-device.ts
Get back the message that reports successful deploy on android device. We've deleted it a couple of commits ago.
=> Show message after successful deploy

mobile/android/android-device.ts
Merge release in master pre 1.5.0
=> Merge release in master pre 1.5.0

bootstrap.ts, codeGeneration/code-entity.ts, codeGeneration/code-generation.d.ts, codeGeneration/code-printer.ts, commands/generate-messages.ts, declarations.d.ts, errors.ts, file-system.ts, messages/messages.d.ts, messages/messages.ts, mobile/mobile-core/devices-service.ts, options.ts, resources/messages/errorMessages.json, services/message-contract-generator.ts, services/messages-service.ts, test/unit-tests/messages-service.ts
References [#300626](http://teampulse.telerik.com/view#item/300626)
Introduces a new messaging service which reads messages from given **.json** files. There is one such file placed in this library and is loaded by default. Its **keys can be overriden** by providing other, client-specific .json files containing the same keys but with a different value.
In order to achieve autocompletion on referencing these error messages a new generation command is introduced - **dev-generate-messages**. It produces a .d.ts interface, as well as a .ts implementation file, which contain all keys from all provided json files as properties. If run as-is it generates files for the client from which the command is launched. If `--default` option is provided generates messages in common lib only.
In order to …
=> Restructure error messaging

sys-info-base.ts
`pod --version` command, which is used to determine the version of cocoapods, might return some warnings.
Here's a sample output:
```
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
0.39.0
```
Make sure to get the real version in this output (0.39.0).
=> Fix getting of cocoapod version

definitions/mobile.d.ts, mobile/ios/ios-application-manager.ts, mobile/ios/ios-core.ts
The console is not release if `tns livesync ios` command is executed
=> Release the console after livesync command and fix a typo.

services/html-help-service.ts
When we search for correct help page, we have to list dev commands as well as we want to show the help of dev-test command in NS CLI.
=> List dev commands when searching help pages

mobile/ios/ios-core.ts
Different node versions have different behaviors of timers. In some cases, on some machines we throw error that future is resolved more than once.
Prevent it.
=> Prevent Future resolved more than once errors

bootstrap.ts, declarations.d.ts, dispatchers.ts, sys-info-base.ts, test/unit-tests/sys-info-base.ts, winreg.ts
When cocoapods are not installed on Mac machine, doctor is failing.
Fix this by skipping match check in case pods are not installed.
Add basic unit tests for doctor service.
Add unit test for the failing cocoapods check.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1245
=> Fix cocoapods check and add unit tests for doctor service

mobile/android/logcat-helper.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1130
=> Don't duplicate the messages from logcat

declarations.d.ts, options.ts
This option is used by both CLI's, so add it to common options.
=> Add --template option

definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/ios/ios-application-manager.ts
We have different cases when we can start the application, based on current platform and device platform.
Add `canStartApplication` in applicationManager's which evaluates all circumstances and can be used to check if we are able to start the application on device.
=> Add canStartApplication to applicationManager

sys-info-base.ts
When paths to android tools are undefined, we call childProcess exec and spawnFromEvent with undefined commands.
This leads to futures left behind as childProcess cannot be created and our future is never resolved.
Do not call exec and spawnFromEvent in case command is empty.
=> Fix getSysInfo when paths to android tools are undefined

definitions/mobile.d.ts, mobile/ios/ios-emulator-services.ts, services/usb-livesync-service-base.ts
Do not restart the application when .xml or .css file is deleted and build correct path to files on ios simulator.
=> Still fixing removed files from iOS simulator

mobile/mobile-core/devices-service.ts
When deploying application in Proton, Android application must be started on the device.
Fix this by calling correct start method.
=> Start application on Android device when deploying via Proton

README.md, appbuilder/proton-bootstrap.ts, appbuilder/proton-logger.ts, bootstrap.ts, package.json
Fix `EPERM: operation not permitted, write` error when started from Proton installation and trying to write to stdout.
The process does not have stdout, so all logger calls will cause such failure.
Introduce new logger, special for Proton, that will not do anything at the moment. We'll extend it in the future to send messages to Proton with the messages.
Set version to 0.1.3
=> Introduce proton logger

appbuilder/proton-bootstrap.ts, definitions/mobile.d.ts, mobile/android/android-device.ts, mobile/constants.ts, mobile/ios/ios-device.ts, mobile/mobile-core/android-device-discovery.ts, mobile/mobile-core/devices-service.ts, mobile/mobile-core/ios-device-discovery.ts, package.json
* Crash when iPhone is not trusted.
* Crash when error is raised during device detection. From now on the error is caught. We'll report it to Proton (this will be handled in separate PR).
* Crash when trying to provide sysLogs for unauthorized devices.
* In case more than one Android device has "USB Debugging" disabled, we were showing only one device. Show all devices from now on.
* status - string, describing the status of the device, can be `Connected` or `Unauthorized`. Could be expanded in the future.
* errorHelp - in case status is `Unauthorized` we provide some information to the user how to resolve the issue. In case status is `Connected` this should be null.
* color - Color of the device. Not mandatory part of the Interface. Currently provided only for iOS devices.
Change the way …
=> Improve device discovery and fix some issues

mobile/android/android-device.ts, mobile/constants.ts, mobile/ios/ios-device.ts, mobile/mobile-core/android-device-discovery.ts, package.json
Fix android device detection - remove method was not correct and was never removing device.
Fix ios device detection - always set status to Unreachable when there's error.
Change name of Unauthorized status to Unreachable.
=> Fix android and ios device detection

README.md, appbuilder/device-log-provider.ts, bootstrap.ts, commands/device/device-log-stream.ts, definitions/mobile.d.ts, helpers.ts, mobile/android/android-log-filter.ts, mobile/device-log-provider.ts, mobile/ios/ios-log-filter.ts, mobile/log-filter.ts, mobile/logging-levels.ts, mobile/mobile-core/devices-service.ts, package.json, test/unit-tests/android-log-filter.ts, test/unit-tests/appbuilder/device-log-provider.ts, test/unit-tests/ios-log-filter.ts, test/unit-tests/log-filter.ts
* Add AndroidLogFilter - specific filtering for Android devices
* Add IOSLogFilter - specific filtering for iOS devices
* Add LogFilter class - common filtering logic. Resolves androidLogFilter or iOSLogFilter based on the input.
* Show full output when `<cli> device log` command is used.
* Add unit tests for androidLogFilter
* Add unit tests for iOSLogFilter
* Add unit tests for LogFilter
* Make sure isFuture method returns boolean.
* Expose setLogLevel method in devicesService (used for Proton)
=> Add device log filtering

definitions/mobile.d.ts, mobile/mobile-core/android-device-discovery.ts, test/unit-tests/decorators.ts, test/unit-tests/mobile/android-device-discovery.ts
Add tests for androidDeviceDiscovery that will verify the behavior.
Fix issue in decorators tests, where global $injector had been incorrectly reset.
=> Add tests for androidDeviceDiscovery

README.md, mobile/ios/ios-proxy-services.ts, mobile/mobile-core/devices-service.ts, services/messages-service.ts
When we deploy on iOS devices, the first sent package sometimes receives error code 21. It turned out this error is not breaking the deployment, so ignore it once and continue deploying.
The error occurs only when we have parallel futures executing for device detection.
Also when error is raised during application starting, we reject the Promise for deploy on device. This is not correct, so ignore such errors and resolve the promise.
One fix to rule them all: http://teampulse.telerik.com/view#item/307776
=> Fix deploy on iOS devices

declarations.d.ts, services/typescript-compilation-service.ts
Currently TypeScript projects are compiled by enumerating their files and spawning tsc with specific options.
We do not need this when tsconfig.json exists as the TypeScript compiler uses it directly.
Add new method to TypeScriptCompilationService in order to omit our own options passed to tsc.
Remove initialize method as it is not used anymore.
=> Add default compilation for TypeScript files

child-process.ts, definitions/mobile.d.ts, definitions/node-fibers.d.ts, errors.ts, mobile/android/android-debug-bridge.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts, test/unit-tests/stubs.ts
Order of commits:
When staticConfig is not registered (in our tests), when uncaught exception is raised, the listener fails with error that staticConfig cannot be resolved. This makes it hard for debugging. Try-catch the resolve of staticConfig and set the disalbeAnalytics to true when staticConfig cannot be resolved.    This way the tests will not have to register analyticsService.
Update `fibers.d.ts` with new property that exists in the object - error - required for new unit tests. When the future throws, calling `future.get()` throws. In such cases first check future.error, for example:
```TypeScript
let futures: IFuture<void>[] = [];
// fill lots of futures
try {
Future.wait(futures);
} catch(err) {
}
_.each(futures, f => {
if(!f.error) {
f.get();
}
})
```
Currently when adb fails, …
=> Add isAppInstalledOnDevices public method

services/analytics-service.ts
Remove the message of the exception as it is already printed in most of the cases.
=> Fix exception tracking message

mobile/android/android-device-file-system.ts, services/project-files-manager.ts
On some Android devices the `android-runtime` cannot delete the files in `/data/local/tmp/<app id>/fullsync` directory.
The next time when the application is started, runtime reads the fullsync directory and replaces the real application with content of fullsync dir.
So the app does not start as it is not full app.
Fix two issues - first one is missing `chmod` command in the file that we are generating.
As we cannot spawn chmod of all files directly, due to some command line limitations, we are writing the command in a file, transfer the file on the device and execute it.
BUT, we've lost the command in this commit https://github.com/telerik/mobile-cli-lib/commit/6d52c6ab9b51aaac7b5fae7e4412c0f58737fcf1
In fact our file contains only list of files and when trying to execute it on the …
=> Fix livesync on Android devices and Genymotion emulator

mobile/mobile-core/devices-service.ts
Revert change applied in this commit - https://github.com/telerik/mobile-cli-lib/commit/065512bd01ccae6dfd4648244c0ee21bcf5abf19#diff-3afe2bc0eef11fb206a6cfb650f4057fL213
The idea was to speed up actions executed on multiple devices. However in our current code is not able to work this way.
For example `tns run android` is trying to execute multiple simultaneous builds and it fails. Same will happen with livesync in some cases.
The problem is with the action that's passed for each device. Until we fix the other code, let's keep the old behavior.
=> Revert parallel execution of action on multiple devices

mobile/android/android-device-file-system.ts, test/unit-tests/mobile/android-device-file-system.ts
Currently we are validating only the shasum of the files in order to detect which one are changed and sync only them.
However this is not correct as the file may be on a different location, but without changing its size.
Also in case you copy some of your files, their shasums might be the same as the original file.
In case the original file is already synced, its hash size will be found in the "oldShasums" and the new file will not be copied.
Validate by using both path and hash.
Fix unit tests and add some new ones.
=> Fix detection of changed shasums

errors.ts
When tracking uncaught exceptions, we do not have fiber, but our code works with futures. So it fails with error "Can't wait without fiber".
Fix this by creating fiber.
=> Fix error for missing Fiber when tracking uncaught exceptions

services/usb-livesync-service-base.ts
`appbuilder livesync --watch` fails with error when file is saved. The problem is in code used for NS CLI, which returns null instead of future.
=> Fix livesync --watch

services/livesync-service-base.ts
When you try to livesync on multiple devices and application is not installed on more than one, calling `tns livesync <platform>` installs the application only on one of them.
There's warning in the output that the application is not installed for each of the devices, but it is installed only on one of them.
The problem is the current logic that is executed for each device - as we want to build only one, in case the app is already built, we've skipped the install part for all devices except the first one.
So we have to build once, but install the built package on all devices where the app does not exist.
=> Fix livesync on multiple devices when app is not installed

child-process.ts
In childProcess we print the arguments passed to a method. In case it does not have arguments, we our method for printing fails.
Fix the method by checking arguments before printing them.
=> Fix childProcess arguments printing

declarations.d.ts, options.ts, services/project-files-manager.ts, services/project-files-provider-base.ts, test/unit-tests/mobile/project-files-manager.ts, test/unit-tests/project-files-provider-base.ts
Fix LiveSync of platform specific and configuration specific files by extracting logic for parsing filename and use it in NS CLI.
Add ProjectFilesProviderBase class that holds the logic, so it can still be used from ProjectFilesManager.
Add --release option to common options so when `tns livesync <platform> --release --watch` is used, the files will be processed correctly.
Add tests for the new ProjectFilesProviderBase class.
=> Fix sync of platform specific and config specific files

options.ts, services/project-files-provider-base.ts, test/unit-tests/common-options.ts
Move common options tests to common lib (from icenium-cli), where they belong.
Also modify the $options visibility to protected, so it can be called from classes that extend ProjectFilesProviderBase.
Add -r as shorthand for --release.
=> Move common options tests to common

declarations.d.ts, prompter.ts
Implemented to facilitate calls requiring nonempty strings.
=> Add option for (dis)allowing an empty string in prompter

bootstrap.ts, declarations.d.ts, mobile/ios/device/ios-device.ts, services/xcode-select-service.ts, test/unit-tests/xcode-select-service.ts
Used to communicate with `xcode-select` command line tool.
Currently only used for getting the path to various subdirectories of Xcode.app but can be extended to invoke `switch` or even `install` if needed.
=> Introduce xcode-select-service

mobile/mobile-core/devices-service.ts
When there are no devices attached, CLI should start emulator and execute the action on it.
For example calling `tns run android` when there are no devices attached, the devicesService should start emulator and run the application in it.
Currently this is not working as the startEmulator method is starting the instance and then calls method for device detection.
However the checkForDevices method is async and it does not guarantee when the devices will be detected.
Instead use startLookingForDevices which is synchronous.
=> Fix starting of emulator when no devices are attached

services/analytics-service.ts
In case eqatecMonitor is not started it may take a while to send the usage report.
In case the process exits, the report is never sent.
So wait for sending it.
=> Wait for sending usage report

.vscode/settings.json, appbuilder/appbuilder-bootstrap.ts, appbuilder/declarations.d.ts, appbuilder/mobile-platforms-capabilities.ts, appbuilder/project-constants.ts, appbuilder/project/cordova-project-capabilities.ts, appbuilder/project/nativescript-project-capabilities.ts, appbuilder/project/project-base.ts, appbuilder/proton-bootstrap.ts, appbuilder/providers/appbuilder-livesync-provider-base.ts, appbuilder/providers/device-app-data-provider.ts, appbuilder/providers/livesync-provider.ts, appbuilder/providers/project-files-provider.ts, appbuilder/services/livesync/android-livesync-service.ts, appbuilder/services/livesync/companion-apps-service.ts, appbuilder/services/livesync/ios-livesync-service.ts, appbuilder/services/livesync/livesync-service.ts, appbuilder/services/path-filtering.ts, declarations.d.ts, services/livesync-service-base.ts, tsconfig.json
Move some files from icenium-cli to common lib, introduce new interfaces and implement
* Livesync for Proton - expose new method:
```JavaScript
require("mobile-cli-lib").liveSyncService.livesync(deviceLiveSyncInfos, pathToProject, filesToSync)
.then(function(result) {
console.log("Finished");
}).catch(function(err) {
console.log("Error: ", err);
console.log(err.stack);
})
```
* Expose method to get Companion app identifiers:
```JavaScript
var companionAppId = require("mobile-cli-lib").companionAppsService.getCompanionAppIdentifier(framework, platform));
```
* Introduce cable LiveSync for NativeScript applications
=> Implement LiveSync for Proton and for NS apps

services/auto-completion-service.ts
When path to node has spaces (C:\Program Files) the child process exec cannot run the command. Need to place it in "" to run it without errors.
=> Fixed the autocomplete

commands/analytics.ts, commands/help.ts, commands/post-install.ts, declarations.d.ts, helpers.ts, services/analytics-service.ts, services/commands-service.ts, test/unit-tests/analytics-service.ts
* Move tracking of environment setup at the end of post install. This way we'll first ask the users if they want to be tracked and after that track the InstallEnvironmentSetup only for the users who allowed us to track them.
* Explicitly call the check for analytics status on post-install. Currently the question was raised as we were calling autocomplete command. On each command we check if user had answered the question and if not - we ask him. Make the action more visible (in the code).
* When asking user if analytics tracking should be enabled, currently we start the analytics monitor before showing the question. This is incorrect as when the users does not answer immediately, we end up with very long sessions (for example user keeps the terminal opened and the question just stays …
=> Fix analytics tracking of users

prompter.ts
In order to prevent double printing of stdout data, CLI mutes the stdout. However this is done in prompter constructor, so every class, that depends on the prompter, automatically mutes the stdout.
Basically CLI mutes the stdout on almost all commands. This causes issues when `tns plugin add` command is used and the plugin wants to prompt the user for something on postinstall.
Fix this by calling mute exactly before prompting the user and calling unmute immediately after user sends his answer.
=> Unmute stdout after prompter execution

appbuilder/declarations.d.ts, appbuilder/project-constants.ts
When building the project with --download the configuration files for all platforms should be downloaded in .ab folder
=> Move additional files in .ab folder

appbuilder/providers/device-app-data-provider.ts, appbuilder/services/livesync/ios-livesync-service.ts
Change LiveSync directory for NativeScript projects on iOS devices to be the place where ios runtime will use as entry point.
=> Change LiveSync directory for iOS NativeScript

appbuilder/providers/device-app-data-provider.ts, services/livesync-service-base.ts
* Fix LiveSync issue for NativeScript iOS projects, when application is not installed on device and `$ appbuilder livesync ios` is called - this should install the application. Instead it does nothing.
* Fix LiveSync to companion app when application is not installed on device. Currently it was trying to install the application instead of sending the app to companion.
=> Fix livesync issues when app is not installed on device

declarations.d.ts, options.ts, services/hooks-service.ts
When `--no-hooks` is passed on command line, the hooks will not be executed.
=> Introduce `hooks` option

appbuilder/providers/device-app-data-provider.ts, appbuilder/services/livesync/ios-livesync-service.ts, mobile/constants.ts
Fix LiveSync for iOS Simulator by changing:
* Root Project Path for NativeScript applications, which was incorrectly including "app" dir.
* Fix path where we copy files to be the iOS LiveSync Dir (/Library/Application Support/LiveSync) - for Cordova projects, the LiveSync plugin automatically gets all files from bundle to this directory, so next time when CLI livesyncs to simulator, we place the new files in the bundle. LiveSync plugin will not pull these changes in the LiveSync dir, so we have to do it manually.
Move LiveSync constants in the constants file.
=> Fix LiveSync for iOS Simulator

README.md, appbuilder/declarations.d.ts, appbuilder/device-emitter.ts, appbuilder/providers/device-app-data-provider.ts, appbuilder/services/livesync/companion-apps-service.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/mobile-core/devices-service.ts
Add events which are raised when applications are installed/uninstalled on devices.
DeviceEmitter will raise:
* `applicationInstalled` when app is installed on device. Passed params are device identifier and application identifier.
* `applicationUninstalled` when app is removed from device. Passed params are device identifier and application identifier.
* `companionAppInstalled` when one of the companion apps is installed on device. Passed params are device identifier and framework (cordova or nativescript).
* `companionAppUninstalled` when one of the companion apps is removed from. Passed params are device identifier and framework (cordova or nativescript).
Add new public method to companionAppsService:
`getAllCompanionAppIdentifiers` - returns JSON object with all companion app …
=> Add application changed events

commands/doctor.ts, commands/post-install.ts, declarations.d.ts, helpers.ts
When executing tns doctor outside of project if the nativescript cli needs update it will print information for the available update.
If tns doctor is executed in project it will check the installed runtimes versions and the nativescript core modules version and print information if an update is needed.
Add tns info command to display versions information for NativeScript CLI, core modules and runtimes.
=> Add warn for new versions

declarations.d.ts, services/livesync-service-base.ts
Add before livesync hook to be able to control the livesync data. Added property in livesync service to force full sync which will be passed to the livesync data.
=> Disable fast livesync with hook

declarations.d.ts, helpers.ts, services/xcode-select-service.ts, test/unit-tests/xcode-select-service.ts
The logic is now used more than once and has to be extracted to a common place. Add test
Re-targeted from https://github.com/telerik/mobile-cli-lib/pull/644
=> Move logic for getting Xcode version to xcode-select-service

helpers.ts
When using the filter `x => x` the number 0 gets filtered out incorrectly
=> Compare versions properly

services/analytics-service.ts
Do not track setting of feature-usage-tracking and error-reporting when we are asking for confirmation of Feature Usage Tracking.
=> Fix analytics tracking

declarations.d.ts, sys-info-base.ts
This gem is a dependency of CocoaPods but users may not want to install or use CocoaPods. However this gem is crucial for performing local builds for the iOS platform.
Ping @rosen-vladimirov for a quick review
=> Gather information about xcodeproj ruby gem's location

verify-node-version.ts
Due to issue in npm versions 3.0, 3.5.1, 3.7.3 (may be more 3.x versions) the NativeScript node_modules are removed before the preuninstall script is executed and it fails.
The issue is logged in the npm repository: https://github.com/npm/npm/issues/8806 but it is not fixed in version 3.1.1 as commented in the discusion.
=> Hide npm preuninstall errors

declarations.d.ts, definitions/user-settings.d.ts, services/analytics-service.ts, services/user-settings-service.ts
Each sessions count should be tracked per project for which it is started. Currently we were using the same counter for all sessions.
Fix this by using separate counter for each project.
Remove the old key ("SESSIONS_STARTED") and use it as current value for the new key (`SESSIONS_STARTED_<analytics_project_key>`) in case it existed.
=> Track sessions count per analytics project

mobile/ios/simulator/ios-simulator-application-manager.ts
Currenly when `tns livesync ios --watch` is used for iOS Simulator, CLI starts the application on device and prints filtered logs.
The filter is based on the process id of the currently started application. During livesync, the application is restarted, which changes the PID of the running process.
In this case we should start filtering based on the new PID.
=> Fix printing of simulator logs when livesyncing

mobile/android/android-emulator-services.ts
When starting Android emulator the output from the `net` `data` event always contains \r\n and when using `EOL` from `os` to split it on Mac or Linux it contains \r and then the parsing fails.
=> Fix output parsing when connecting to started emulator

README.md, appbuilder/declarations.d.ts, appbuilder/services/livesync/livesync-service.ts, declarations.d.ts, definitions/mobile.d.ts, mobile/device-app-data/device-app-data-factory.ts, package.json, services/livesync-service-base.ts
Change LiveSync API for Proton to return array of Promises.
For each device we return Promise which contains information which livesync operation are successful.
Update device-app-data-factory to accept parameter if the LiveSync is for Companion app or not.
=> Change LiveSync API for Proton

mobile/mobile-core/ios-simulator-discovery.ts
When simulator is closed, we do not report it and we do not send deviceLost event.
=> Fix simulator device detection

mobile/ios/device/ios-core.ts
On Mac `receiveMessage` method returns only the last message instead of all. It contains only the Success/Fail status, so we decide that there are no applications that can be LiveSynced. This breaks Proton.
=> Fix isLiveSyncSupported check for iOS devices on Mac

README.md, appbuilder/services/livesync/livesync-service.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, package.json
The event loop is really messed with our setInterval that should detect devices. As it's running on 500ms, when livesync operation is in progress, it constantly fails.
As a workaround, stop the device detection while livesyncing and start it again after that.
Try moving device detection to a separate PR in the bright future.
=> Fix livesync for iOS on Mac

mobile/mobile-core/ios-simulator-discovery.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
In case you do:
- start simulator
- close simulator
- start simulator
We are not reporting it as started the second time, as we are not clearing our cache. Clear the cache and add unit tests.
Use deep clone of the simulator object returned by ios-sim-portable in order to make the code testable.
=> Fix detection when iOS Sim is closed and reopened

README.md, mobile/ios/simulator/ios-simulator-application-manager.ts, package.json
Allow using .zip files for deploy to iOS simulator - if the passed path is .zip, extract it to temp dir and pass the temp dir to the simulator.
=> Allow using .zip files for deploy to iOS simulator

bootstrap.ts, commands/help.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/android/android-debug-bridge-result-handler.ts, mobile/android/android-debug-bridge.ts, mobile/android/android-device-file-system.ts, mobile/android/android-device-hash-service.ts, mobile/android/android-device.ts, mobile/android/android-emulator-services.ts, mobile/android/device-android-debug-bridge.ts, mobile/android/logcat-helper.ts, mobile/mobile-core/android-device-discovery.ts, static-config-base.ts, test/unit-tests/mobile/android-device-discovery.ts
The android debug bridge result handler checks if there are any errors after executing adb command.
Errors are copied from https://github.com/android/platform_frameworks_base/blob/master/core/java/android/content/pm/PackageManager.java and the handler checks if the result contains any of the errors.
The non-device Android debug bridge must be separated from the device-specific Android debug bridge. Non-device Android debug bridge can be injected through constructor and the device-specific Android debug bridge can be resolved using the $injector. This way the device-specific Android debug bridge will be unique for each device.
The adb commands should be executed through the custom adb wrapper to use the error handling.
=> Add Android debug bridge result handler

static-config-base.ts
When getting the adb file path need to use childProcess not our adb wrapper becaulse it will fail with `Segmentation fault node "<file-path>" "$@"`.
=> Fix Segmentation fault

mobile/android/android-debug-bridge.ts
Some adb commands like adb start-server return array of strings not object with stdout need to check if stdout is undefined or null because if it is empty string it will return incorrect result.
=> Change adb result handling in adb wrapper

README.md, appbuilder/declarations.d.ts, appbuilder/device-emitter.ts, appbuilder/proton-static-config.ts, appbuilder/services/livesync/livesync-service.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
When new device is attached, common lib is trying to get all of its applications and to send intents for each of them in order to check is livesync supported for them.
This leads to tens or even hundreds of started adb processes. At some point, when you have more than one device, adb cannot handle the whole flow and it suicides itself.
After that you have to kill manually the only existing adb process or it will never detect any devices.
In order to prevent this behavior, change the way of detection is LiveSync supported. Expose new public method that will be used to check if LiveSync is supported for specific devices (and one appIdentifier).
Remove the reporting of isLiveSyncSupported in the "applicationInstalled" event.
=> Fix starting many adb processes

appbuilder/services/livesync/livesync-service.ts
Currently LiveSync to companion app via Proton fails with error that application is not installed. In fact it fails because we've not changed the appIdentifier to be the companion app's identifier.
=> Fix LiveSync to companion app

README.md, appbuilder/services/livesync/livesync-service.ts, mobile/mobile-core/devices-service.ts, package.json
On Mac OS X, there's no need to call iOSDeviceDetection process in setInterval, as when runLoopRun is called once (first time before the setInterval), after that it starts calling our callback whenever a device is changed (attached/detached).
So ignore the code on Mac.
=> Disable iOS device detection interval on OS X

definitions/semver.d.ts
When checking if platform dependency is installed in the current project before adding the platform need to check if the current version is valid or check in the node_modules directory for the installed plugin version.
=> Fix add android platform dependencies

appbuilder/appbuilder-static-config-base.ts, appbuilder/declarations.d.ts, appbuilder/project/project-base.ts, appbuilder/proton-static-config.ts, definitions/mobile.d.ts, mobile/constants.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
Currently when deploying NativeScript apps on Android via Proton, we are unable to start the application, as we pass incorrect StartPackageActivity.
Fix this by extracting the correct names in constants. When deploy is called from Proton side, we'll set the correct name in the `$project`.
After that the execution of start method will use the value from `$staticConfig`. StaticConfig will return the value of project's property.
`deployOnDevices` method now has additional argument - framework. If it is passed and the provided value is NativeScript, we'll use the NativeScript's StartPackageActivity.
In all other cases we'll use Cordova's StartPackageActivity.
=> Allow starting of NativeScript apps on Android via Proton

mobile/ios/device/ios-proxy-services.ts
It looks like this error does not prevent us from working correctly. Just log it as warning.
=> Ignore error code 21 for iOS Devices

mobile/ios/device/ios-device.ts
It looks like that even when some operation fails, we are still able to execute iOS Device related operations.
So do not set the status to UNREACHABLE in case some of the operations that are not connect (or pairing) fails.
Set the status to CONNECTED on every successful operation.
=> Do not set iOS Status to UNREACHABLE in all cases when smth fails

appbuilder/services/livesync/livesync-service.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/device/ios-proxy-services.ts, mobile/mobile-core/devices-service.ts
Currently we are using AMDeviceLookupApplications to check the installed applications on iOS.
As we need information is LiveSync supported for all user's applications, we have to make another call through installationProxy, that returns both CFBundleIdentifier and IsLiveSyncSupported property.
So we do not need the first call at all as the second one gives us all the required information.
Also cache the installation proxy instead of creating new one each time.
Use the cached data for isApplicationInstalled method. In case the app is not there, applicationInstalled will be raised when it is installed.
Cache the Installation Plist service, so we'll have only one instance per each iOS device.
=> Use installationProxy to get installed applications on iOS

bootstrap.ts, definitions/mobile.d.ts, mobile/mobile-core/android-process-service.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
To forward the port need to find the current process id, then use the process id or the application identifier to find the abstract port, find available port on localhost and do the forwarding.
Implements http://teampulse.telerik.com/view#item/313437.
Add method which finds applications which are available for debugging. To determine which applications are available for debugging need to run adb shell cat proc/net/unix and find the applications which have abstract ports like @webview_devtools_remote_[pid], @[app_id]_devtools_remote or @[app_id]-debug.
=> Map Android WebView ports to local ones on demand

mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/device/ios-proxy-services.ts
Revert caching of iOS services as this caused several issues with multiple data parsing, keeping sockets opened, etc.
Make sure to close the socket after each operation.
In case you call isApplicationInstalled before checkForApplicationUpdates, the cache will not be populated and the result will always be false.
In case there's no data in the cache, call checkForApplicationUpdates.
=> Remove caching of iOS services

appbuilder/providers/device-app-data-provider.ts, services/livesync-service-base.ts
Fix livesync of application when it is not installed on device. Currently it is running two builds for Android.
=> Fix livesync when app is not installed

README.md, appbuilder/proton-bootstrap.ts, mobile/ios/device/ios-device.ts, mobile/ios/device/ios-proxy-services.ts, package.json
Most of the iOS File related operations may fail on Mac OS X, but after retrying them, they succeed.
Retry the operations several times and fail in case they do not succeed.
Also fix error: "Futures left behind" during transfer of files when `ensureDevicePathExist` throws (the future had not been resolved).
Set iOS Device status to Unreachable only in constructor, not when some operation fails.
Most of the operations may fail a single time only, so the device is not Unreachable.
When device is trusted, we will remove current instance of iOS Device and we'll create new one, where the status will be Connected.
=> iOS Device operations fixes

appbuilder/declarations.d.ts, appbuilder/project-constants.ts
The projects created with Ionic CLI have Ionic specific srtucture and some changes should be done to transform the project to AppBuilder hybrid project.
Rerouting index.html file should be created to pointto the Ionic index.html file in the www folder.
The resources should be copied from the resource folder to App_Resouces folder. Android resources should be renamed and put to the appropriate folders. Windows Phone 8 splashscreen should be JPG not PNG.
The information in the config.xml of the Ionic project should be split and moved to the appropriate AppBuilder folders. Also the sources of the resources should be changed to be relative to the newly added platform specifix config.xml.
All AppBuilder default plugins should be removed from the plugins folder to reduce the size of the …
=> Integrate Ionic CLI projects with AppBuilder CLI

mobile/android/logcat-helper.ts
`adb logcat` remains live on Mac OS X when common-lib process dies. Kill it in such cases, so we'll not have orphans when common-lib is used in Proton.
=> Kill adb logcat process when parent process dies

verify-node-version.ts
Update message for Node.js 0.10.x deprecation and add additional arguments to verification method - CLI's name and version in which support for Node.js 0.10.x will be removed.
=> Pass CLI Name to verifyNodeVersion

appbuilder/project/project-base.ts, appbuilder/services/livesync/livesync-service.ts, definitions/logger.d.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
LiveSync plugin requires application to be started on device at least once in order to report that LiveSync for current app is enabled.
The reason is that when the application is started for first time, LiveSync plugin bootstraps the app, by replacing some files. In case we send our newly changed files before that and start the application, LiveSync plugin will replace our files with the original ones from .apk.
So for Proton, start the application when `isLiveSyncSupported` called. The workflow is:
* Call `Build and Deploy` from Proton
* Install the app
* common-lib raises `appInstalled` event
* Proton catches `appInstalled` and calls `isLiveSyncSupported` for the specific devices and application.
* common-lib starts the application and after that calls isLiveSyncSupported.
The other …
=> Start application on isLivesSyncSupported call from Proton

README.md, appbuilder/services/livesync/livesync-service.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, package.json, test/unit-tests/mobile/devices-service.ts
Remove isLiveSyncSupported method as isAppInstalledOnDevices returns the same information, so it should be used.
Also from now on, when `isAppInstalledOnDevices` is called, it will start the application, if possible.
Add new method to check if companion app is installed on devices.
`isCompanionAppInstalledOnDevices(deviceIdentifiers: string[], framework: string): Promise<IAppInstalledInfo>[]`
The difference from `isAppInstalledOnDevices` is that this method will not start the application on device.
Set version to 0.12.0
=> Remove isLiveSyncSupported from public API

appbuilder/services/livesync/android-livesync-service.ts, appbuilder/services/livesync/livesync-service.ts, declarations.d.ts, definitions/mobile.d.ts, mobile/android/android-livesync-service.ts, mobile/local-to-device-path-data-factory.ts, mobile/mobile-core/devices-service.ts, services/livesync-service-base.ts
Add public method in liveSyncService that should be used to delete files when LiveSync operation is in progress.
This way, when user deletes file in Proton, the application will call `liveSyncService.deleteFiles` method for it and it will be removed from device.
=> Add public API for deleting files during liveSync operation

README.md, decorators.ts, mobile/mobile-core/devices-service.ts, package.json
Add postAction on exportedPromise decorator. This action will be called when all Promises are fulfilled.
Stop deviceDetection interval when starting deployOnDevices as it causes issues when deploying on iPhones from Mac.
In the post action start the device detection interval.
=> Add post action on exportedPromise decorator

README.md, appbuilder/services/livesync/livesync-service.ts, definitions/mobile.d.ts, mobile/mobile-core/android-device-discovery.ts, mobile/mobile-core/devices-service.ts, package.json
When you have deploy operation or livesync operation, we must stop device detection and checking for application changes as it breaks the deployment on iOS Devices.
The problem is that in case ANY async callback is called during uploading .ipa file to iOS Device for installation, the installation fails with different errors (PackageExtractionFailed, PackageVerificationFailed, etc.).
Add new future inside the setInterval and in case it's not resolved, the next time when setInterval is called, it will see that there's a future pending and will not schedule new execution.
Also when stopDeviceDetectionInterval is called and the future from setInterval is still pending, wait for it before starting the real operation.
=> Stop device detection and checking for application updates

README.md
The namespace for IAndroidApplicationInformation is not necessary.
=> Remove the namespace from the documentation

appbuilder/declarations.d.ts, appbuilder/project-constants.ts, appbuilder/project/project-base.ts, appbuilder/providers/device-app-data-provider.ts, appbuilder/services/livesync/companion-apps-service.ts, appbuilder/services/livesync/ios-livesync-service.ts, declarations.d.ts, mobile/constants.ts, mobile/mobile-core/android-process-service.ts
Move TARGET_FRAMEWORK_IDENTIFIERS from $projectConstants (available in AppBuilder CLI only) to constants.
This way we can use it in common lib and all CLIs directly.
=> Move TARGET_FRAMEWORK_IDENTIFIERS to constants

helpers.ts
If passed value is object or number, toBoolean helper method fails as they do not have .toLowerCase() method.
=> Fix error when converting to boolean

appbuilder/providers/appbuilder-livesync-provider-base.ts
Fix LiveSync in AppBuilder and Proton by calling correct method in livesyncProvider.
=> Fix LiveSync in AppBuilder and Proton

appbuilder/services/livesync/livesync-service.ts, declarations.d.ts, services/livesync-service-base.ts
Remove the data.canExecuteFastSync. The check is made in the respective {N} service instead of in the base implementation
=> Execute batch sync when you live syncing application with the --watch option

mobile/mobile-core/devices-service.ts
When `--device` is specified, CLI is trying to find all currently attached devices and check if the passed option is valid. This leads to starting of a setInterval, that is trying to detect when new device is attached.
The setInterval is executed on 2 seconds and it starts iOS related services and adb related services. It looks like this breaks the execution of AFC service.
Fix this by using a method that do not start the setInterval, but detects all currently detected devices.
This fix errors like:
`Error: Unable to close afc file connection: '4361027664'. Result is: '3'`
and
`Error: Unable to write to file: '4361027664'. Result is: '11'`
when `--device` is used.
=> Fix AFC Connection errors when --device is specified

declarations.d.ts, services/livesync-service-base.ts
When the application is installed on device for the first time with the livesync command, it always recompiles the app e.g:
tns livesync ios --watch
=> Fixed: livesync recompiles the app always when first time livesync

commands/device/run-application.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/mobile-core/devices-service.ts
When executing `appbuilder device run appid` outside of project the CLI cannot determine which startPackageActivity name to use - for NativeScript or for Cordova application. The fix is to check where the command is executed and if it is not in project we need to run the adb command for both NativeScript and Cordova projects.
=> Fix device run command

README.md, appbuilder/device-emitter.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/android-process-service.ts, mobile/mobile-core/devices-service.ts
Add `debuggableAppFound` and `debuggableAppLost` events which are raised when an application becomes available for debugging or when an application is not available for debugging anymore.
=> Add events for debuggable apps

.npmignore, README.md, package.json
Set version to 0.16.0
Ignore  .vscode dir and .npmignore file - we do not need them in the npm package.
=> Set version to 0.16.0

README.md, appbuilder/declarations.d.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/android-process-service.ts, mobile/mobile-core/devices-service.ts
When information about debuggable apps is returned, the title property does not give any value. It's not real app title, as when the page is changed in WebView, it will be changed as well. So it is removed now.
Also rename the interface and extract new one, that can be used whenever device identifier and application identifier should be used.
=> Remove title property from debuggable apps info

decorators.ts, package.json, test/unit-tests/decorators.ts
Add more unit tests for decorators and fix some issues that raised during writing tests.
Add `.catch` in the `exportedPromise` decorator in order to prevent "Unhandled Rejection Error" when one of the promises is rejected.
This will not break the current API behavior as the rejected promise will still be returned as result and the consumer of the API can add it's own catch.
The `exported` decorator was incorrectly using the `target` instead of the object from injector.
=> Add more unit tests for decorators

appbuilder/project/project-base.ts
Instead of caching the old keys, do a deep diff between configuration-specific data and current project data.
=> Remove logic about storing configuration-specific keys

appbuilder/mobile/appbuilder-companion-device-app-data-base.ts, appbuilder/mobile/appbuilder-device-app-data-base.ts, appbuilder/providers/device-app-data-provider.ts, mobile/device-app-data/device-app-data-base.ts, services/livesync-service-base.ts
When checking if the livesync is supported and the application is not installed the result is false and we need to deploy the application on the device and check again.
=> Check if livesync is supported

services/analytics-service.ts
Currently when we check if analytics is sending information we always wait at least one second. In fact we do not have to wait when analytics is not sending data at the moment.
Improve this check and also speed up the unit tests of analytics service a lot.
=> Improve check for sending analytics data

appbuilder/project/project-base.ts, appbuilder/project/project.ts
When we integrate experimental version of NativeScript we need to upload new package of the CLI in npm with the updated nativeScript-migration-data.json file so the users can use the new version.
It will be better to download the nativeScript-migration-data.json file when NativeScript related command is executed.
=> Download nativeScript-migration-data.json file

appbuilder/declarations.d.ts, appbuilder/device-emitter.ts, mobile/application-manager-base.ts, test/unit-tests/appbuilder/device-emitter.ts, test/unit-tests/mobile/application-manager-base.ts
Detecting found and lost debuggable apps is depending on lodash's `differenceBy` method. It's been using old value of property name for comparison ("packageId" instead of "appIdentifier").
Use correct property which fixes debuggableAppFound and debuggableAppLost event.
Add unit tests for ApplicationManagerBase.
- Fix type of object used in deviceEmitter's handler for "debuggableAppFound" and "debuggableAppLost" events.
Add unit tests for deviceEmitter
=> Fix debuggableAppFound and debuggableAppLost events

README.md, appbuilder/project/project-base.ts, package.json
Fix maximum call stack size exceeded when reading project data. Clone the cached object, not the one that calls the same method.
=> Fix maximum call stack size exceeded when reading project data 

bootstrap.ts, declarations.d.ts, mobile/mobile-core/android-process-service.ts, services/net-service.ts
Fix mapAbstractToTcpPort, which was incorrectly reading device files instead of getting them from local machine.
`mapAbstractToTcpPort` must return the same port in case there's already forwarded port for this application - call `adb -s <device id> forward --list` and parse result in order to return the already created one.
Fix returning multiple `chrome` apps when getting debuggable applications. In fact they are all the same, so we can just return the unique values.
Fix getting PIDs of processes, which was returning incorrect results when we have apps with similar names (com.telerik.Debugger and com.telerikDebuggerTests).
In order to get free port on local machine, introduce `$net` dependency, which is wrapper for Node.js's net module. Use OS's logic that prevents EADDRINUSE error - …
=> Fix debug operations for Proton

README.md, appbuilder/device-emitter.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/android-process-service.ts, mobile/mobile-core/devices-service.ts, package.json, test/unit-tests/appbuilder/device-emitter.ts, test/unit-tests/mobile/application-manager-base.ts
Implement `debuggableViewFound`, `debuggableViewLost` and `debuggableViewChanged` events that will be raised when there's a change in application's debuggable views.
=> Implement new events for debuggable WebViews detection

README.md, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/mobile-core/android-process-service.ts, mobile/mobile-core/devices-service.ts, package.json
When there are webviews inside NativeScript application, mobile-cli-lib does not return them in getDebuggableApps as they have the same appIdentifier.
Also when trying to map abstract port for NativeScript application with WebViews, mobile-cli-lib finds the WebView first and maps port for it. In order to fix this, add `framework` parameter that will be passed from Proton.
=> Allow debugging of WebViews inside NativeScript applications

appbuilder/project/project-base.ts
Fix starting of NativeScript applications by passing correct startPackageActivityName. Use the framework from projectData in case it exists in order to determine the startPackageActivity.
=> Fix starting of NativeScript applications

mobile/ios/simulator/ios-simulator-application-manager.ts
If the application is not installed and we try to get the plist content of it we will fail.
=> Check if app is installed when getting the parsed plist

appbuilder/project/project-base.ts
We do not need to default to the Cordova start package activity name when we don't have project data because we can try to start NS application and the Cordova name will not work.
=> Fix start package activity name

appbuilder/providers/appbuilder-livesync-provider-base.ts, appbuilder/services/livesync/android-livesync-service.ts, appbuilder/services/livesync/ios-livesync-service.ts, declarations.d.ts, services/livesync-service-base.ts
Introduce platformSpecificLiveSyncServices map that is used in {N} live sync service
Rename the IPlatformLiveSyncService interface because it is more device oriented that platform
=> NativeScript LiveSyncServiceBase refactoring

mobile/application-manager-base.ts, test/unit-tests/mobile/application-manager-base.ts
When this method is executed right after the application is installed, the isApplicationInstalled returns false so we have to explicitly call checkForApplicationUpdates to update the application list. Since the tryStartApplication would fail if the app is not installed, and the exception would be caught, remove the isApplicationInstalled check
=> Remove the check whether the application is installed

test/unit-tests/process-service.ts
When we test the execution of all attached listeners we need to emit SIGTERM because if we emit exit or SIGINT the execution of the tests after this one will fail.
=> Fix process service unit test

appbuilder/appbuilder-bootstrap.ts, appbuilder/declarations.d.ts, appbuilder/project-constants.ts, appbuilder/services/npm-service.ts, constants.ts
Add support for installing npm dependencies. Provide two methods for public API:
- install - installs everything from package.json. In case a specific dependency must be installed, it's described as second argument with its name, version and should `@types` be installed.
- uninstall - uninstalls the specified dependency from both node_modules and package.json. The call will also remove `@types/<dependency>` entry from devDependencies.
Still to do (in separate PRs)
* Add android17.d.ts and ios.d.ts to the project and reference them in .abreferences.d.ts
* Add unit tests
* Update README for new public API (requires bump of version in package.json)
=> Add support for installing npm modules and @types

README.md, package.json
Add description and sample usage for the public methods in our npm service.
New methods:
`install(projectDir: string, dependencyToInstall?: INpmDependency): Promise<INpmInstallResult>` - Installs everything from package.json or specified dependency. In case there's information which dependency to install, the method will check it and install only this dependency and possibly it's @types.
`uninstall(projectDir: string, dependency: string): Promise` - Uninstalls the dependency and the @types/ devDependency. The method will remove them from package.json and from node_modules dir.
=> Add documentation for npm service

appbuilder/providers/appbuilder-livesync-provider-base.ts, declarations.d.ts, services/livesync-service-base.ts
After `platformSpecificLiveSyncServices` was renamed to `deviceSpecificLiveSyncServices` when we try to resolve livesync service we need to use `deviceSpecificLiveSyncServices` instead of the empty `platformSpecificLiveSyncServices`.
=> Fix resolve livesync service

appbuilder/declarations.d.ts, appbuilder/project-constants.ts, appbuilder/project/project-base.ts, appbuilder/services/livesync/livesync-service.ts
Since the users can change the app identifier for Android in Cordova projects by modifying the AndroidManifest.xml and config.xml we need to use the correct id which will be used to build the application on our server.
=> Get the correct app identifier

appbuilder/project/project-base.ts
When we have only AndroidManifest.xml or config.xml in the project and the app id in it is not changed we do not need to throw exception for app id mismatch.
=> Fix error when getting android id

declarations.d.ts, file-system.ts, test/unit-tests/file-system.ts
After we migrate TS projects we should delete the typings directory if it is empty after we remove the tns-core-modules directory.
=> Delete typings dir if it is empty

appbuilder/services/npm-service.ts
When uninstalling plugin, the .abreferences.d.ts file must be regenerated in order to remove the entries from @types, which are removed from the file system.
=> Regenerate .abreferences.d.ts file on plugin remove

appbuilder/project/project-base.ts
When we compare the app identifiers in AndroidManifest.xml and in config.xml in case only one app identifier is changed we need to check if it is changed to a value which is different from the one in .abproject file.
=> Fix get Android app id check

appbuilder/project/project-base.ts
The application identifier written in AndroidManifest is the single source of truth. Ignore the one in config.xml - server will take care of it.
Part of [Set id property in android's config xml automatically](http://teampulse.telerik.com/view#item/320940)
Merge along with https://github.com/Icenium/Ice/pull/6234
=> Remove redundant code for validation of AndroidManifest vs config.xml

appbuilder/declarations.d.ts, appbuilder/services/npm-service.ts, declarations.d.ts, services/plugins/npm-plugins-source.ts, services/plugins/npm-registry-plugins-source.ts, services/plugins/npmjs-plugins-source.ts, services/plugins/plugins-source-base.ts, services/plugins/print-plugins-service.ts
Display fetched plugins.
We should display the fetched plugins in Cordova projects when we list the installed plugins.
Move the prompter in the plugin source and add version parameter when fetching plugin.
=> Improve fetched plugins operations

services/plugins/npm-registry-plugins-source.ts
When we get the author of the plugin first we need to check if there is one.
=> Fix get plugin author

appbuilder/providers/device-app-data-provider.ts
When we create the Android NS companion app device app data we need to pass framework NativeScrit instead of Cordova.
=> Fix NS Companion app livesync

definitions/rimraf.d.ts
When we migrate TS project and we remove the tns-core-modules we use the shelljs to remove the directory but there is some bug when using it - it fails to delete some of the subdirecotries. Thet's why we will use rimraf instead of shelljs.
Related to: https://github.com/Icenium/icenium-cli/pull/1553
=> Use rimraf to remove tns-core-modules

services/plugins/npmjs-plugins-source.ts
When we get the plugins from http://npmjs.org we need to start from page 1 not from page 0 because page 1 and page 0 are the same.
=> Fix get first page plugins trom npmjs twice

mobile/ios/simulator/ios-simulator-application-manager.ts, package.json
On some Mac OS machines, the process for reading iOS Simulator logs does not die when Ctrl + C is used. So CLI's process cannot die as well and Ctrl + Z should be used. However the processes for reading logs remain alive and zombies.
Make sure to kill the process on SIGINT, SIGTERM, etc. This way CLI's process should die as well.
Use new version of ios-sim-portable, where the child process is returned to the CLI, so we can kill it later.
=> Kill the process for iOS Simulator logs on SIGINT

file-system.ts, services/user-settings-service.ts, test/unit-tests/file-system.ts, test/unit-tests/mobile/android-device-file-system.ts
Since our other clients use 2 spaces for indentation in json files we should use 2 spaces too. Since some users are using only the CLI we should not change their current indentation.
=> Keep the current indentation of json files

appbuilder/services/npm-service.ts, declarations.d.ts, http-client.ts
Use npm proxy for connections to registry.npmjs.org. This way in case the user has set a proxy, we'll use it.
CLI makes calls to registry.npmjs.org. But the users can configure different registry (`npm config set registry <...>`), so CLI should respect it instead of calls to `registry.npmjs.org`.
=> Respect npm settings - proxy and registry

appbuilder/services/npm-service.ts, http-client.ts
In case there's no npm proxy, `npm config get proxy` returns string "null" and we think this is the proxy.
This leads to incorrect calls to registry.npmjs.org.
=> Do not use proxy when npm config returns null

declarations.d.ts, services/livesync-service-base.ts, services/livesync/sync-batch.ts, services/typescript-service.ts
When we run the livesync command with the --watch flag the .ts files are not transpiled and there are no new .js files to sync to the device. We should transpile the .ts files before we get the files to sync and remove the .ts files from the sync queue to avoid transpiling twice.
Fixes: http://teampulse.telerik.com/view#item/322155
=> Transpile TS files on file change in livesync

appbuilder/services/npm-service.ts, http-client.ts
Add timeout option to http request which defines the time that we'll wait for response.
In case there's no response, the call will throw error.
Set timeout of 6000 for calls to registry.npmjs.org.
=> Add timeout to http request and use it for calls to npm registry

mobile/ios/device/ios-core.ts
When we use net.Socket we need to use .toString() to get the whole content of the buffer because it may contain many \0 and ref.readCString will return the string which is before the first \0 not the whole content.
Fixes https://github.com/telerik/mobile-cli-lib/issues/723
=> Get full ios logs on mac

mobile/mobile-core/ios-simulator-discovery.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
When we check if there is running simulator we use ps cax but if the simulator is killed for a short period of time after that there is a process listed when using ps cax and we decide that there is a running simulator and then we try to use it but ios-sim-portable returns null. We should check if the simulator returned from ios-sim-portable is not null or undefined in order to continue to work with it.
=> Fix check for ios simulator

mobile/ios/device/ios-device.ts, mobile/ios/device/ios-proxy-services.ts
iTunes has an option to sync changes over wifi for each iOS device. However, for some devices, when trying to start the installation_proxy service and `Sync over Wi-Fi` option is enabled, the connection fails.
Catch such cases and show helpful message describing the problem and how to resolve it.
Should help for issues like: https://github.com/NativeScript/nativescript-cli/issues/1398
=> Show helpful information when Sync over WIFI error is detected

services/livesync/sync-batch.ts, services/typescript-service.ts
Fix `livesync <platform> --watch` for NS CLI by removing AppBuilder specific code from SyncBatch.
Also start tsc with `--watch` option when `--watch` is passed.
In SyncBatch remove the files that are will not be synced from the syncQueue.
=> Fix livesync --watch for NativeScript CLI

declarations.d.ts, helpers.ts, services/hooks-service.ts
When we validate the hook arguments we try to resolve all of them but there is one argument which is not registered in the injector - hookArgs. If some hook wants to use it we will try to resolve it and fail. The solution is to skip the validation for the hookArgs argument.
=> Do not try to resolve hookArgs

appbuilder/device-log-provider.ts, bootstrap.ts, definitions/mobile.d.ts, helpers.ts, mobile/device-log-provider-base.ts, mobile/device-log-provider.ts, mobile/ios/ios-log-filter.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/ios/simulator/ios-simulator-device.ts, mobile/ios/simulator/ios-simulator-log-provider.ts, mobile/log-filter.ts, package.json, test/unit-tests/appbuilder/device-log-provider.ts, test/unit-tests/helpers.ts, test/unit-tests/ios-log-filter.ts, test/unit-tests/log-filter.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
iOS Simulator device logs are printed directly to process.stdout from the ios-sim-portable. However this makes it really difficult to filter the logs and provide them to different callers (for example AppBuilder CLI, NativeScript CLI, Proton).
In order to fix this, use the ios-sim-portable just to start the process of getting device logs. Filter them in the CLI itself.
Also change the logic in ios-log-filter to use process pid in case it's passed. For iOS Simulator we have filtered logs based on the PID of the application. With these changes, simulator logs are passed to ios-log-filter, so that's why we need process' PID there.
When application is restarted (during livesync for example), we set the PID again and the filter will use the new PID.
Merge AFTER …
=> Fix getting ios simulator device logs

helpers.ts, options.ts, package.json, test/unit-tests/common-options.ts, test/unit-tests/helpers.ts
The validation of -- options passed on the command line depends on yargs module. Update it to latest versions as the previously used one didn't set correct values of options marked as strings.
Also in our code we pass object of valid options to yargs. Options which have `-` in the name are treated in a special manner in yargs. However instead of passing them with `-`, we pass their secondary representation (remove the `-` and capitalize the next letter).
This way, when the user passes option with `-`, yargs treat it with it's default behavior and does not respect our options for it (as we have not defined that we have option with `-`).
Example:
```JavaScript
var yargs = require("yargs");
var opts = {
"profile-dir": { type: "string" }
};
console.log(yargs(process.argv).options(opts).argv); …
```
=> Fix validation of -- options

file-system.ts
currently if there is no given folder the line:
```typescript
let contents = this.readDirectory(directoryPath).wait();
```
blows up because there is no directory. Currently if directory present, the function will return an empty array.
ping: @rosen-vladimirov
=> if there is no app folder just return an empty array of files

services/process-service.ts
Ctrl+C should work in cases when there are no listeners for exit signals attached
=> Fixed: Ctrl+C should work in cases when there are no listeners attached

verify-node-version.ts
Deprecate support for Node.js 0.12.x as it will not be supported after 2016 by Node.js Foundation.
=> Deprecate support for Node.js 0.12.x

mobile/ios/device/ios-core.ts
The code used to read only the first digit, but according to the documentation the signal code is a two-digit hexadecimal number
With the current version of the runtime the signal that is raised is SIGABRT == 0x06
Fixes https://github.com/NativeScript/nativescript-cli/issues/2053
=> Fix CLI is not disconnected on iOS exception

bootstrap.ts, declarations.d.ts, definitions/prompt.d.ts, helpers.ts, os-info.ts, package.json, prompter.ts, services/analytics-service-base.ts, test/unit-tests/analytics-service.ts, test/unit-tests/mobile/android-device-file-system.ts
Update the TS related dependencies to use TS 2.0 and fix the errors from
the update
=> Use TypeScript 2.0

mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, test/unit-tests/mobile/application-manager-base.ts, test/unit-tests/stubs.ts
Can be useful for some scenarios like granting permissions for application via adb (automating testing process). Granting permissions require app to be deployed on device in order to work, so after-prepare hook cannot be used.
=> Added install hook.

declarations.d.ts, services/livesync-service-base.ts
Instead of using the application's own appid we should use the companion app's appid when performing LiveSync for the companion
=> Fix wrong appid when LiveSyncing to Companion app

mobile/ios/device/ios-core.ts
On iOS 10 devices the device logs contain \n after each line.
When we use readCString for buffers which contain many \0
the method will return the content of the buffer only before the first \0 character.
We need to replace the \0 with "" in order read the whole content.
=> Fix iOS 10 device logs

mobile/ios/device/ios-core.ts
Reverts telerik/mobile-cli-lib#848
The release for this fix is changed to 3.6.2
=> Revert "Fix iOS 10 device logs"

verify-node-version.ts
As old versions of Node.js cannot be used anymore (after transpiling to ES6), we should break the process when such case happens.
Use only var instead of let, const, as only var keyword is supported in Node.js 0.10.x
=> Break CLI process when Node is not supported

helpers.ts, test/unit-tests/yok.ts
As the transpilation had been changed to ES6 instead of ES5, there is a problem, when $injector should resolve lambdas.
When they are transpiled to ES5, they are converted to functions. However in ES6 they are still lambdas and current `annotate` method does not work correctly.
Fix the regex that's used for the parsing and add unit tests for the failing cases.
=> Fix $injector to resolve lambdas

mobile/device-log-provider.ts, mobile/ios/device/ios-core.ts
https://github.com/NativeScript/nativescript-cli/issues/2266
=> Fixed: CLI crashes/stops responding after ~80 console.logs

appbuilder/services/npm-service.ts
We need to set the stdio when installing node modules because nativescript-telerik-ui asks for email in its post-install script and does not check if the terminal is interactive or not. If it is not interactive it will ask for email and out npm install will hang.
=> Set stdio inherit to npm install

commands/device/get-file.ts, definitions/mobile.d.ts, mobile/android/android-device-file-system.ts, mobile/ios/device/ios-device-file-system.ts, mobile/ios/device/ios-proxy-services.ts, mobile/ios/simulator/ios-simulator-file-system.ts, options.ts
This functionality was necessary in order to implement predictable livesync as described here:
https://github.com/NativeScript/nativescript-cli/issues/2153
https://github.com/NativeScript/nativescript-cli/issues/2330
* Removed the watch option from options list. This option is specific for {N} CLI.
=> Implemented get/put file functionality in device file systems

test/unit-tests/android-log-filter.ts
On Windows the unit tests are failing as the end of line is `\r\n`, but android-log-filter tests expect only `\n`.
Use `os.EOL` instead of `\n`, so the tests will pass on all OS.
Issue is introduced in https://github.com/telerik/mobile-cli-lib/pull/864
=> Fix unit tests on Windows

package.json, test/unit-tests/appbuilder/device-emitter.ts, test/unit-tests/decorators.ts, test/unit-tests/helpers.ts, test/unit-tests/mobile/application-manager-base.ts, tsconfig.json
TypeScript 2.0 does not add "use strict"; in files which just declare class and does not export it. This breaks Node 4 because of the class keyword.
=> Update TypeScript to 2.1

decorators.ts, mobile/android/android-device.ts, mobile/mobile-core/devices-service.ts, services/hooks-service.ts
We need to cache the result of the decorated methods for each instance not for all instances. Also we need to add the name of the cached member to the cache property becasue if we do not add it we can't cache other members.
Also we need to execute build and deploy on multiple devices synchronously because the build will fail if the actions are executed for each device in parallel.
There were forgotten console.logs from debugging which are removed.
=> Fix cache decorator

appbuilder/providers/device-app-data-provider.ts, appbuilder/services/livesync/ios-livesync-service.ts, definitions/mobile.d.ts, mobile/android/android-device.ts, mobile/ios/device/ios-device.ts, mobile/ios/simulator/ios-simulator-device.ts
Instead of a function - it doesn't perform any slow operations and can be a get property.
isEmulator was previously a property but was subsequently re-written as a function, however this is no longer necessary.
=> Make isEmulator a get property

sys-info-base.ts
Cli executes system commands, but when they are not critical for the system the OS works fine, but cli fails because it can't find the necessary commands it expects to be there by default. Added some logging for easier tracing in the future. 
related: https://github.com/NativeScript/nativescript-cli/issues/1922
=> added logging when executing system commands

prompter.ts
After removing the fibers we forgot to await the result from the prompt before calling the unmuteStdout method. After this method is invoked the input from the terminal is not accepted.
=> Fix prompter

verify-node-version.ts
In method `verifyNodeVersion`, which is called at the beginning of each CLI, sometimes we have to inform the user that we'll stop support of specific range of Node.js versions in the next release.
So add the logic in the method and each CLI can specify deprecated versions in case it  has to.
=> Add default message when a node.js version is deprecated

constants.ts
We do not need to add .png asset when the project has the 9 patch png version of this asset.
=> Fix ensure all platform assets

mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
It looks like there's some kind of a problem when a Promise is resolved in unref-ed setInterval. Node.js suddenly thinks the process has no more work to do and does not wait for deviceDetectionInterval.
So fix this by calling unref once the Promise is resolved. This allows consecutive executions of setInterval.
This also fixe `<cli name> device` command.
=> Fix deviceDetectionInterval

mobile/ios/simulator/ios-simulator-file-system.ts
In some cases we are not able to sync files to iOS Simulator as chokidar does not raise correct events on macOS when directory is renamed immediately after it's being created.
After adding a file to this directory we throw ENOENT, as such dir does not exist in Simulator's dir. In order to fix this, ensure the directory exist in the simulator.
=> Fix ENOENT when sync to iOS simulator

appbuilder/services/npm-service.ts
During migration from fibers to promises, we've lost one `!` in the check if npm package has typings in `@types` repo.
This led to incorrect behavior:
- typings of packages, which are available in `@types`, are not installed (for example `lodash`).
- trying to install plugin, which does not have typing in `@types` leads to error (something like `Error while installing dependency: Command npm.cmd failed with exit code 4294963238.`).
Fix the check (add the missing `!`) which will fix the incorrect behavior.
=> Fix check if package has `@types`

appbuilder/services/npm-service.ts
CLI tries to get information for specific version of a package by calling registry.npmjs.org.
It looks like recently the registry.npmjs.org has been modified and when passing version as query parameter, it just disregards it. Now the version is part of the URL itself.
Old: `http://registry.npmjs.org/rosen-test-npm-package?version=1.0.0`
New: `http://registry.npmjs.org/rosen-test-npm-package/1.0.0`
So fix CLI's code where we are generating the URL.
=> Fix getting info from registry.npmjs.org for specific version

appbuilder/services/npm-service.ts
CLI needs information for specific versions of packages. However registry.npmjs.org have broken something and the URL we've been using (`http://registry.npmjs.org/<package_name>?version=<version>`) does not work anymore.
Instead it returns information for all versions.
We've tried calling `http://registry.npmjs.org/<package_name>/<version>`, which seemed to work fine, but it turned out it has a lot of issues with scoped dependencies.
Issues are describe [here](https://github.com/npm/registry/issues/130).
In order to fix CLI and allow installation of all plugins, get the full information from the registry and find only the info we need for the specified version.
=> Fix getting package.json from npm registry (again)

declarations.d.ts, services/typescript-service.ts
The first problem is when in the tsconfig.json file in the compilerOptions there is a property with array value. We need to pass the array values correctly to the tsc command.
The second problem is with TypeScript 2.1 output. When there is an error in the output while transpiling TS 2.1 will make the `error` word red. This means that the actual autput will look like this: `[91merror [0m TS2304`. We need to update our regular expressions to match the new output.
Fixes: http://teampulse.telerik.com/view#item/329315
=> Fix transpilation problems

services/livesync-service-base.ts, services/process-service.ts, services/typescript-service.ts
Fix several missing `await`s in LiveSyncServiceBase which caused unexpected behavior during livesync. For example livesync to ION leads to error when adding a file in some cases.
Fix gaze to skip `node_modules` and `platforms` directories - in the current state, when we are inside Angular project, the node_modules directory contains tens of thousands of files. Gaze starts painfully slow and utilizes 100% of the CPU.
So ignore these directories.
Fix killing of TypeScript process started with `--watch` option. It failed with error `Cannot read property '_handle' of null`. Fix this by passing correct `this`.
When we are inside TypeScript process, we attach to process's SIGINT signal in order to kill TypeScript Watcher. However Node.js decides that we have to handle all other currently living …
=> Fix livesync issues

mobile/android/android-emulator-services.ts
See more info: https://github.com/NativeScript/nativescript-cli/issues/2576
_Problem_
When `tns run/debug android` is ran, with no running emulator, the emulator was started, the app was installed, but not launched. The problem is after the emulator was started we couldn't get the name of the emulator.
Related issue: https://github.com/NativeScript/nativescript-cli/issues/2486
=> emulator name was undefined because we missed an await

child-process.ts, declarations.d.ts, definitions/mobile.d.ts, mobile/ios/ios-log-filter.ts, mobile/log-filter.ts, services/livesync-service-base.ts, services/project-files-provider-base.ts, test/unit-tests/ios-log-filter.ts, test/unit-tests/log-filter.ts
That way services become stateless and can be used in long-running processes
=> Get rid of $projectData dependency in services

declarations.d.ts, definitions/mobile.d.ts, mobile/android/android-emulator-services.ts, sys-info-base.ts, test/unit-tests/sys-info-base.ts
Due to changes in Android SDK, we have to update the checks in CLI. While gathering system information, we check the android executable, which is no longer returning correct results.
In order to fix this, we rely on the emulator executable, which is the real thing we need as it is the one that allows us to work with Android Emulators.
Fix sys-info checks and get correct path to emulator according to latest changes.
=> Fix getting info for Android tools

appbuilder/device-log-provider.ts, definitions/mobile.d.ts, mobile/ios/ios-log-filter.ts, mobile/log-filter.ts, test/unit-tests/ios-log-filter.ts, test/unit-tests/log-filter.ts
We have added one parameter in the filter method which we do not need and we do not respect it when we call the method. The solution is to remove it.
=> Fix device log filter

file-system.ts
When the --copy-to flag in the CLI is set, we use the CopyFile method from FileSystem to copy the built file - AppName.app to the destination. Mac OS resolves this file as a directory in the terminal and the cp command fails with "omitting directory" because it's missing the -R flag.
=> Fix copy of MobileApp.app build file after creation

mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
When devices are not with status Connected, we should not check for application updates on these devices as the code will fail.
Fix this in the deviceDetectionInterval logic, so long living processes will work correctly.
=> Do not check for application updates for Unreachable devices

mobile/ios/device/ios-application-manager.ts
When we are unable to install app on iOS device, we show warning and we continue the execution. However we have to throw error in such cases.
=> Throw correct error when unable to install app on iOS

decorators.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/decorators.ts
The exportedDecorator promise may have postAction. In case the postAction returns a promise, we'll not wait for its execution and we'll return the result to the caller.
This leads to problem when there are two consecutive calls to deployOnDevices - after the first one finishes, we start the deviceDetectioninterval, but we do not wait for it to finish the first execution.
When the second deploy starts it sees there's a running interval, clears it and waits for the promise to be resolved. However we've never started the execution, so the promise is never started, so it is never resolved.
Fix this by:
- clearing the interval after waiting for current promise to be resolved
- fix the exportedPromise decorator to wait for the first execution of the startDeviceDetection interval to finish
=> Fix device detection interval deadlock

definitions/mobile.d.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-device-operations.ts
We need to pass the project name instead of the app identifier to kill the application on the simulator.
=> Fix stop application on iOS simulator

appbuilder/services/livesync/livesync-service.ts, appbuilder/services/npm-service.ts, decorators.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, services/typescript-service.ts, test/unit-tests/decorators.ts, test/unit-tests/mobile/devices-service.ts, test/unit-tests/mocks/public-api-mocks.ts
Delete `@exportedPromise` decorator as we no longer need it
Stop stopping device detection interval when deploying on iOS devices. These operations no longer conflict as the code is located in an external dependency.
=> Stop stopping device detection interval

mobile/ios/simulator/ios-simulator-file-system.ts
When copying directory over an existing directory and the LiveSync is working it tracks that a directory should be created and tries to re-create it on the device with "mkdir" which conflicts". The errors observed are:
`Unable to sync files. Error is: Multiple errors were thrown:
EEXIST: file already exists, mkdir '/Users/yosifov/Library/Developer/CoreSimulator/Devices/BF4EC4A7-0D62-46F0-BF90-CD2BFA071A23/data/Containers/Bundle/Application/171F45A9-E810-4FBF-AFAB-A6715B00EFB0/Test.app/app/dummy/dummy'`
The issue is fixed by just ensuring the directory exists, so that we don't try to create it if it already exists.
=> Fix directory creation to not try to recreate it if it exists

mobile/ios/device/ios-application-manager.ts, mobile/ios/device/ios-device-operations.ts, mobile/ios/ios-log-filter.ts
We need to check if the justlaunch flag is passed before we set the should dispose property to false. If we set it to false unconditionally when we pass justlaunch flag the process will never exit.
=> Fix ios-device-operations dispose

mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
When in debug mode we should respect the passed platform and search only for devices for the respective platform. If we have devices from both android and iOS we recognized them both as valid devices and started an emulator.
=> Add filter by platform when searching device

test/unit-tests/mobile/devices-service.ts
added unint tests for newly added functionality that takes care of starting emulators if there's the need.
related PR: https://github.com/telerik/mobile-cli-lib/pull/918
=> added unit tests for startEmulatorIfNecessary method in devicesService

mobile/ios/device/ios-device-operations.ts
For older iOS devices, they cannot be enlisted by the:
`tns device ios`
command, as they're discovered slower. I've tested with 3.0 seconds which is double the current value and it seems to have worked every time for an old iPad of ours. 
Best,
Yosif
=> Increase discover iOS devices timeout

mobile/ios/device/ios-device-operations.ts
In order to improve the hard-coded "wait for 5 seconds" timeout and then check if some iOS Devices have been detected, we change to iteratively checking for iOS Device results on every 0.5 seconds, so that the 5 seconds would be a worst case for very very slow iOS devices or no iOS devices connected at all.
=> Adding tick-tack mechanism to incrementally wait for devices

commands/proxy/proxy-get.ts, commands/proxy/proxy-set.ts, declarations.d.ts, services/proxy-service.ts
* Prompt the user for a full url in case an incomplete or incorrect one is passed (for example 127.0.0.1 instead of http://127.0.0.1
* Fix UI bug in `proxy get` command where `:` is displayed twice after protocol (i.e. http:://127.0.0.1)
* Print proxy info after `proxy set`
=> Validate proxy url

appbuilder/services/npm-service.ts, commands/proxy/proxy-set.ts, declarations.d.ts, http-client.ts, services/credentials-service.ts
Fix using proxy on macOS and Linux - the getCredentials method should not fail - it should return null on OSes that are not supported.
Fix using npm proxy - CLI automatically detects the proxy and uses it for calls to npm registry. However we have not set the rejectUnauthorized variable and all requests to our internal npm proxy were failing. So in such cases set the rejectUnauthorized to the value of strict-ssl npm config variable.
=> Fix proxy usage on macOS and Linux and fix using npm proxy

constants.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
* Throw more meaningful error when trying to start ios simulator on non-Darwin OS
* Do not throw inside `resolveEmulatorServices` method - one should still be able to resolve on non-Darwin as long as one does not start an emulator
Ping @rosen-vladimirov @Plamen5kov
=> Fix AppBuilder unit tests

declarations.d.ts, definitions/mobile.d.ts, helpers.ts, mobile/mobile-core/devices-service.ts, services/net-service.ts
We need to add debug service to the public API of the {N} CLI. This service should have method which starts debugging and returns the chrome devtools url. With this service it will be possible to use the CLI as a library and start debugging.
This PR includes:
- Return the results from the action in devicesService.execute(action)
=> Add debug method to the public API

helpers.ts
The connectEventually method should use a promise for its factory parameter. Make the method async and pass a method that returns a promise.
=> Pass promise to connectEventually method

helpers.ts, test/unit-tests/helpers.ts
Add new helper method to get the process ID of an application from iOS Simulator Logs. Whenever we start an application on iOS Simulator, in its logs we can find the PID of the process in the following format:
```
<app id>: <app id>: <PID>
```
Add unit tests for the method.
=> Add helper method for getting PID of app from iOS Sim logs

helpers.ts
Its purpose is to attach an event handler, await an action and detach the event handler
=> Add event emitter helper method

mobile/ios/device/ios-device-operations.ts
Currently we have logic to find the intially attached (at the moment of starting the CLI) iOS devices. Its executed at the beginning of each device related commands and it checks on 500ms for device found.
However this is a problem as we may find one device and skip the others devices (in case more than one device is attached). So first CLI operations are excuted only for one device. The next operations however are executed over all devices found. For example `tns run ios` we execute several operations - install on all devices, upload files to all devices, etc. However in case the install operation is executed, only the first device is discovered. After that the upload files operations are executed on all devices. Due to the fact that the application is not installed on the other devices, …
=> Increase the timeout of initial ios device detection

mobile/mobile-core/android-process-service.ts
When you can debug NativeScript application, there must be a unix socket including the application identifier on the device. CLI searches the currently running sockets and searches for `<appid>-debug`. However with latest (3.0.0) runtime, the socket is called `<appid>-inspectorServer`. Fix regex to work with both of the versions.
NOTE: I'll add tests later.
=> Fix getting debuggable NativeScript apps

mobile/android/android-device-file-system.ts
Pushing files as part of the livesync procedure on Android doesn't always update parent directories' permissions on the device unless the changes require a rebuild of the application, at which point they will be included in a list of files and directories to be chmod`d.
I propose that files being pushed in that temporary directory always have their parent's permissions explicitly set to 777 to allow their removal when necessary.
=> Chmod parent dirs when syncing files on Android

mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
In case there's no devices attached and no emulators running, trying `<cli name> devices <platform> --available-devices` will start emulator.
In order to fix this, modify the `startEmulatorIfNecessary` method to skip the starting in case `skipInferPlatform` option is passed. This option indicates that we are not concerned of specific platform, so the method does not know which is the target platform for which to start emulator.
Add unit test for this behavior.
=> Do not start emulator when `--available-devices` is passed

definitions/yok.d.ts
Add Generics for two of the methods in the injector, which will allow us to skip explicit casts. Most useful in tests. For examle:
Before:
```TypeScript
const a: ISomeInterface = testInejctor.resolve("a");
```
Now:
```TypeScript
const a = testInejctor.resolve<ISomeInterface>("a");
```
=> Add generic method to injector's .d.ts

definitions/mobile.d.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, package.json
When Xcode 8 or later is installed, ios-sim-portable will spawn `xcrun simctl terminate <device id> <app id>` in order to stop the application.
For earlier version the command for stopping the app is `killall <app name>`. So pass correct args to the method.
NOTE: Merge only after the ios-sim-portable version is bumped (i.e. after merging https://github.com/telerik/ios-sim-portable/pull/90).
=> Pass correct args to ios-sim-portable's stopApplication

declarations.d.ts, errors.ts
In case `printCommandHelp` fails (when for example CLI doesn't have permissions to write to the `--profile-dir`) we get an uncaught exception.
Ping @yyosifov @rosen-vladimirov
=> Try catch printCommandHelp

services/analytics-service-base.ts
When passing UserId to the Eqatec we're currently passing the Promise. We should pass the awaited promise though, as the eqatec library works with string/guid and doesn't work with the promise, therefore all our 3.x users are saved under the same UserId currently.
=> Fix UserId passing to the Eqatec

mobile/ios/simulator/ios-emulator-services.ts
In case there are spaces in path to the executable (node) or in the args, we are unable to send notification. Replace the usage of childProcess.exec with childProcess.spawn, which handles the spaces correctly.
=> Fix posting notification to iOS Simulator

appbuilder/device-emitter.ts, bootstrap.ts, constants.ts, definitions/mobile.d.ts, mobile/mobile-core/device-discovery.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/appbuilder/device-emitter.ts, test/unit-tests/mobile/android-device-discovery.ts, test/unit-tests/mobile/devices-service.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
Provide a way for extensions to plug their own `IDeviceDiscovery` instances. 
`$devicesService` will call `startLookingForDevices` for every one of them and make sure to attach to `deviceLost`/`deviceFound` events
Ping @rosen-vladimirov @TsvetanMilanov @yyosifov
=> Add a way to plug device-discoveries

appbuilder/device-emitter.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/appbuilder/device-emitter.ts
Make `DevicesService` extend `EventEmitter` and emit `deviceLost`/`deviceFound` events so that `DeviceEmitter` can emit them ahead.
=> Emit events comming from custom device discoveries

definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts
We need this flag, so that we don't fire up the Simulator/Emulator when we are executing:
`tns build {platform} --forDevice`
as obviously we don't need the Simulator/Emulator and we need to build ipa/apk for real device.
=> Adding isBuildForDevice flag

services/auto-completion-service.ts
1. When we turn the autocomplete ON, for users which don't have `.bash_profile` we create one and add `source ~/.tnsrc` there.
2. This breaks users without `.bash_profile` files, as their Terminal has automatically been picking `.bashrc` and now it's not `sourced` in `.bash_profile`, therefore they lose their environment variables which is bad.
3. So we're left sourcing the .tnsrc file only in `.bashrc` and `.zshrc`. In case user has bash_profile, he would have sourced the `.bashrc` there.
=> Remove .bash_profile alter for autocomplete #1358

services/user-settings-service.ts
If the user didn't have ~/.local/share/.nativescript-cli we create it for them and if the setup is ran with `sudo` the owner of all these directories would be root.
Now we track what will be created and after the creation we `chown` them.
=> Save all unexistent folders and chown them after creation

appbuilder/project/project-base.ts
* This is breaking {N} CLI
* Not necessary for Cordova as they come from templates. Also if
one deletes them, it is expected to get error.
http://teampulse.telerik.com/view#item/345348
ping @Mitko-Kerezov @TsvetanMilanov
=> Do not create debug & release config files by default

commands/analytics.ts, declarations.d.ts, services/analytics-service-base.ts, test/unit-tests/analytics-service.ts
Fix analytics, so we'll no longer track information for users, who have not allowed us to do so. There are several problems:
* Whenever the terminal is not interactive and we do not know if user allows us to track them, we set the value of TrackExceptions to true. Also we immediately send information to Analytics that we've set the value to true. So all CI builds are tracked as new users, as we start a session for them and send the value of TrackExceptions (enabled).
* `setStatus` method almost always sends data to Analytics. This method should not send information. It does not care if we have allowed to be tracked - it always sends data. Remove this logic.
* `tns usage-reporting <value>` and `tns error-reporting <values>` always send information to Analytics - in fact the commands are …
=> Fix analytics

definitions/mobile.d.ts, mobile/ios/device/ios-device-operations.ts, mobile/mobile-core/devices-service.ts, mobile/mobile-core/ios-device-discovery.ts
Provide an option to avoid waiting for the time interval when the method is called from Fusion.
=> Do not wait for ios device when Fusion start.

commands/device/list-devices.ts, mobile/application-manager-base.ts, test/unit-tests/mobile/application-manager-base.ts
When `skipDeviceDetectionInterval` option is not passed to `devicesService`, it does not wait the default timeout (6 seconds) for looking for iOS devices.
It takes some time to detect the devices, but we resolve the promise immediately (as the deviceDetection interval will report the new devices later).
However `tns devices` command is a short-living process and it exits before receiving the iOS devices. Fix the command by passing `skipDeviceDetectionInterval` option.
In reinstallApplication we always call uninstallApplication even when the app is not installed. This produces confusing warnings on stdout.
Add check and call uninstallApplication only when app is installed.
=> Fix not listing iOS devices and confusing messages during reinstall app

definitions/plist.d.ts
plist module has build event that is missing from our .d.ts
=> Add build method to plist module

commands/device/list-devices.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
DevicesService.initialize method has option called `isBuildForDevice`. Its real purpose is to disable start of simulator, so rename it and use it on correct places.
=> Rename isBuildForDevice option to skipEmulatorStart

Gruntfile.js, commands/analytics.ts, messages/messages.ts, package.json, services/analytics-service-base.ts, services/message-contract-generator.ts
Some rules in our tslint.json require passing `--type-check` flag to `tslint` executable.
However grunt-tslint does not support it. So remove the `grunt-tslint` and spawn the `tslint` via npm script.
Add the new `tslint` script, so now the project can be linted by calling:
* grunt lint
* grunt tslint:build /for backwards compatibility/
* npm run tslint
Fix the errors that are received after passing `--type-check` flag.
Disable all linter errors for all automatically generated files (for messages).
=> Replace grunt-tslint with direct calling to tslint

definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts
`devicesService.getDevice` method returns device instance based on specified device identifier or number (from the list of devices).
Make it public, so it can be used in `tns debug <platform>` command.
=> Make devicesService.getDevice public

mobile/ios/device/ios-application-manager.ts
Cache the startDeviceLog method to ensure that we are attached only once to the device log.
[#2941](https://github.com/NativeScript/nativescript-cli/issues/2941)
=> Do not attach to the device log on every application start.

definitions/mobile.d.ts, mobile/mobile-core/android-device-discovery.ts, mobile/mobile-core/devices-service.ts, mobile/mobile-core/ios-device-discovery.ts, mobile/mobile-core/ios-simulator-discovery.ts, test/unit-tests/mobile/android-device-discovery.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
This PR is part of the resolution of https://github.com/NativeScript/nativescript-cli/issues/2361.
The device discovery services didn't check the platform parameter before performing the validations needed for the specified platform.
The resolution is to always pass platform parameter to the device discovery services if specified and add a platform check inside each device discovery service.
=> Add check in iOS device discovery if platform is Android.

definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/android/android-log-filter.ts, mobile/device-log-provider-base.ts, mobile/device-log-provider.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/mobile-core/android-process-service.ts, test/unit-tests/android-log-filter.ts
https://github.com/NativeScript/nativescript-cli/issues/2818 - When an app was started the CLI's logging filter would parse each incoming adb line and check it against a regex that either `JS:` was the tag used, or that any of the [accepted tags](https://github.com/telerik/mobile-cli-lib/compare/pete/log-by-pid-android?expand=1#diff-db4bc9bdec0f0e3438155588e7c23c1aR38)'s string was contained within the logcat line.
That would at times return incorrect, or incomplete logs.
Read the process id for the application process from adb, then filter logs by the pid.
=> Filter android logs by process id

definitions/mobile.d.ts, mobile/android/android-device-file-system.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/device/ios-device-file-system.ts, mobile/ios/simulator/ios-simulator-file-system.ts
When uploading files on devices/emulators, we are executing either `transferDirectory` or `transferFiles` methods of the specific device instance.
However for Android devices, the transferDirectory method has some logic to transfer only modified files (based on shasums from previous execution). So it doesn't really transfer the directory, but just several files.
For LiveSync purposes it is important to know which are the tranferred files, so change the return type of `transferDirectory` method to return the exact files that we've sent to device.
Try-catch the stop of iOS Application as it may fail in some rare cases - in this case just retry it.
=> Return the real transferred files when transferDirectory of device fs is called

declarations.d.ts, helpers.ts, services/livesync-service-base.ts, services/project-files-manager.ts, services/project-files-provider-base.ts, test/unit-tests/mobile/project-files-manager.ts, test/unit-tests/project-files-provider-base.ts
Respect prepare/build configuration when preparing project files.
https://github.com/NativeScript/nativescript-cli/issues/2934
=> Filter configuration specific files

services/hooks-service.ts
Some plugins have hooks which `throw` strings instead of `new Error`s.
If this is the case we should display said string instead of `undefined`.
Ping @rosen-vladimirov @nadyaA @TsvetanMilanov
=> Throw correct error on hook execution

services/xcode-select-service.ts, sys-info-base.ts
_problem_
related issue: https://github.com/NativeScript/nativescript-cli/issues/2810
`getxcodeversion` returning null isn't handled correctly in `tns doctor`
_solution_
handle erroneous case and remove unnecessary code
=> fix getxcodeversion usage

declarations.d.ts, errors.ts
In case the code inside our unhandled rejection handler fails, it will throw another unhandled rejection and we may end up with infinite loop.
In this case try-catch the whole code inside the unhandled rejection and in case error is arised, exit the process. We cannot console.log the error as even this operation might fail.
=> Fix infinite loop of unhandled rejections

mobile/android/android-application-manager.ts, test/unit-tests/android-application-manager.ts
_problem_
`monkey` is a tool used for testing, not for production use and we shouldn't use it since it's a tool used and built for stress testing. It has random behavior and it's not recommended for production use and therefore we are replacing `monkey` with the recommended `am` tool.
Fix Issue: https://github.com/NativeScript/NativeScript/issues/4591
_solution_
Use `am` tool instead to start the application by it's activity identifier which is a combination of the package name and the default activity. 
Example for such an identifier would be: `org.nativescript.appname/com.tns.MainActivity`
=> use am start instead of monkey to start application

services/hooks-service.ts
Some hooks can reject their promises without error.
We need to check if we have an error before we try to get some information from it.
=> Fix the error handling in hooks execution

constants.ts, mobile/android/android-emulator-services.ts, mobile/mobile-core/devices-service.ts
This fixes https://github.com/NativeScript/nativescript-cli/issues/2728. Before a simulator with default preference was started when using  `tns run ios --device "fake"` and nothing else happens. Now a descriptive error is show to the user.
SHOULD NOT BE MERGED BEFORE - https://github.com/telerik/ios-sim-portable/pull/92
=> Fix simulator started on run with fake device id.

commands/proxy/proxy-set.ts
Log a message instructing the user to run the `proxy set` help command to find out how to setup the `npm` and `Gradle` proxy configurations.
Implemented as suggested in https://github.com/NativeScript/nativescript-cli/issues/2816
Related: https://github.com/NativeScript/nativescript-cli/pull/3004
=> Print message when successfully setting the tns proxy configuration

services/html-help-service.ts
Replace `<br>` in markdown help with new line. Also fix the replacement of `<span>` elements - we've been incorrectly replacing all new lines before span element.
=> Do not show `<br>` in terminal

services/project-files-provider-base.ts
In case `filePath` is `false`-like we'll get an error when calling `parseFile`.
The error is `Cannot read property 'match' of null`
=> Safeguard against empty filePaths

declarations.d.ts, definitions/mobile.d.ts, mobile/ios/device/ios-application-manager.ts
Extract some interfaces so that they may be reused on multiple occasions.
=> Extract some interfaces

bootstrap.ts, declarations.d.ts, package.json, services/lockfile.ts, services/user-settings-service.ts
Add new lockfile service (use lockfile npm package) and lock all operations for reading/writing user-settings.json.
These operations may be executed in different processes, so they must be synced between them.
=> Add lockfile service and lock operation for writing user settings file

services/analytics-service-base.ts, test/unit-tests/analytics-service.ts
Whenever a new eqatec monitor is started, we should track the version of Node.js. However, the current code was calling `trackFeatureCore` which always tracks to the Eqatec Analytics projects used for Feature trackings.
This way, when any eqatec monitor is started, we've been sending information for Node.js version to the feature tracking projects. Fix this by passing the api key of the project in which we want to track the information.
Also fix the user sessions count - whenever `start` method is called, we are constructing analytics settings (which increases the counter of current user sessions with 1) and pass this to `startEqatecMonitor` method.
At this point we check if we've already started this monitor and in case not, we do not call start again. However, the values in …
=> Fix tracking of Node.js version in Eqatec and user sessions count

mobile/ios/device/ios-device-operations.ts
After disposing set `this.deviceLib` to `null` in order to prevent any future disposals.
Ping @TsvetanMilanov
=> Clear deviceLib instance on dispose

mobile/ios/simulator/ios-simulator-log-provider.ts, package.json
Part of the fix for https://github.com/NativeScript/nativescript-cli/issues/3141#issuecomment-333449119.
Log format for iOS 10.3: "Oct  3 19:07:55 machinename cliapp[15339]: CONSOLE LOG file:///app/main-view-model.js:18:20: Test Console fix..."
Log format for iOS 11: "2017-10-09 13:34:38.527844+0300  localhost cliapp[22235]: (NativeScript) CONSOLE LOG file:///app/main-view-model.js:18:20: Test Console fix.."
=> Fix iOS11 Simulator log

helpers.ts, services/hooks-service.ts
Whenever a before-hook returns a function it will be used instead of the original method.
When executing such a substitute function it receives a pointer to the original one as well as all its arguments.
Ping @TsvetanMilanov @nadyaA @rosen-vladimirov
=> Allow hooks to provide implementation for decorated methods

appbuilder/device-emitter.ts, constants.ts, definitions/mobile.d.ts, mobile/ios/device/ios-device-operations.ts, mobile/ios/device/ios-device.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/appbuilder/device-emitter.ts
In case iOS Device is detached, the `IOSDevice` instance is kept alive. The reason is the handler for device logs, that `IOSDevice` passes to `iOSDeviceOperations`.
As `iOSDeviceOperations` is still alive, the `IOSDevice` instance is also alive. Reattaching the same device will cause duplicate logs. Detaching and attaching it again will lead to additional logs.
In order to fix the issue, convert `iOSDeviceOpertations` to event emitter and emit event when there's data for logging. Each `IOSDevice` will add handler for the event and will do its logic.
In case device is detached (i.e. `DeviceLost` event is fired in `DevicesService`), call a newly added method to the specific `IDevice` instance. It's purpose is to clean the used resource.
For iOS device, this method will remove the handler …
=> Fix leaking handlers for iOS device logs

bootstrap.ts, commands/help.ts, commands/post-install.ts, declarations.d.ts, definitions/config.d.ts, errors.ts, services/commands-service.ts, services/dynamic-help-service.ts, services/help-service.ts, services/html-help-service.ts, static-config-base.ts, test/unit-tests/services/help-service.ts, test/unit-tests/stubs.ts
In case any command fails, we execute help command in order to show the help content. This leads to multiple trackings, i.e. - user executes only one command, but in Analytics we see two commands.
Instead of executing help command, introduce new method in htmlHelpService, that prints the help to the terminal and call it instead. Use the same method in the help command itself.
Rename htmlHelpService to helpService - it has been incorrectly named from the beginning.
Remove `helpTextPath` from staticConfig interface - this property is not used for more than 2 years.
Introduce tests for `helpService` - get the tests from AppBuilder CLI.
=> Do not track help command when other command fails 

appbuilder/proton-static-config.ts, commands/post-install.ts, commands/preuninstall.ts, declarations.d.ts, definitions/config.d.ts, options.ts, services/lockfile.ts, services/proxy-service.ts, services/settings-service.ts, static-config-base.ts, test/unit-tests/common-options.ts, test/unit-tests/services/settings-service.ts, test/unit-tests/stubs.ts
Currently CLI's configuration directory is used from `$options.profileDir`. When user passes `--profileDir <path>`, the `$options.profileDir` value is populated.
In case user does not pass anything, a default value is set. All services that require configuration directory use the `$options.profileDir`. However, this causes several issues:
- `$options` is intended for use only when CLI is used as a standalone command line. In case you are using it as a library, the `$options` object will not be populated.
- Unable to test local installations of extensions when CLI is used as library - there's no way to set the custom profileDir when using CLI as a library. So the extensions are always loaded from the default location.
In order to resolve these issues, move the logic for profileDir in …
=> Use profileDir from settingsService

services/help-service.ts, test/unit-tests/services/help-service.ts
In case user executes:
- `tns help` - we should show the default index.html help with all commands
- `tns --help` - we should show the default command line help generated from index.md file with all commands
This has been broken during changing html-help-service to help-service.
Fix the default behavior and add tests for it.
=> Fix showing default help (from index.md)

services/hooks-service.ts
In case you need a hook to be executed outside of process, you should place correct shebang at the beginning of the file and CLI should spawn it.
However, this is not working at the moment, as when CLI detects that the hook should be spawned, it just does nothing. The code is incorrectly placed inside the `if` for in process execution. This causes another issue - in case a hook returns a function, which returns falsey value, we decide the hook should be executed outside of process and spawn a new Node.js process to execute the hook. So we execute it twice.
Fix the if-else logic, so the hooks will work correctly.
=> Fix execution of hooks outside of process

appbuilder/device-emitter.ts, appbuilder/proton-static-config.ts, bootstrap.ts, commands/help.ts, commands/post-install.ts, commands/preuninstall.ts, constants.ts, declarations.d.ts, definitions/config.d.ts, definitions/mobile.d.ts, errors.ts, mobile/ios/device/ios-device-operations.ts, mobile/ios/device/ios-device.ts, mobile/mobile-core/devices-service.ts, options.ts, services/commands-service.ts, services/dynamic-help-service.ts, services/help-service.ts, services/hooks-service.ts, services/html-help-service.ts, services/lockfile.ts, services/proxy-service.ts, services/settings-service.ts, static-config-base.ts, test/unit-tests/appbuilder/device-emitter.ts, test/unit-tests/common-options.ts, test/unit-tests/mobile/android/logcat-helper.ts, test/unit-tests/services/help-service.ts, test/unit-tests/services/settings-service.ts, test/unit-tests/stubs.ts
Cherry-picked in release:
- Fix unit tests on Windows (#1019) 80fe24c09c58acab00c7e200c05e2751774f8ef0
- Expose getUserAgent in the analyticsSettingsService (#1020) eac6e6bec934f92edae1bbb8b12e845ba8aa4bb0
- Fix leaking handlers for iOS device logs (#1022) c6853d39fb9aaaaf68e13af766c77f638eec527a
- Do not track help command when other command fails (#1021) c93c34b20c8dfb2ccbff579c3d3be85c80778e7d
- Rename html-help-service.ts to html-service.ts (#1021) b5fe5ff7e2db9cc3870c347655f38b21d1e24506
- Use profileDir from settingsService (#1023) 25c9f0fcc582be04516a23a06260255c0210413b
- Fix showing default help (from index.md) (#1024) b034b304395e616b83d3007aeaa98298ceef2944
- Fix execution of hooks outside of process (#1026) 6918147a223080bee4b7f05a65d12256c17e17fc
=> Cherry-pick commits for {N} CLI 3.3.1 release

README.md, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/devices-service.ts
Expose API for getting installed applications for a specific device when CLI is required as library. Add the new method to `devicesService`.
=> Expose API for getting installed applications

helpers.ts, services/hooks-service.ts, test/unit-tests/helpers.ts
Whenever executing a hook we try and pass the `projectDir` to the hook, however we expect the original method, marked with `@hook` to either have the actual property `projectDir` as an argument or at least have an argument, named `projectData` from which we can get the `projectDir`.
This is incorrect, as the `projectDir` property may be nested in some argument further down.
Recursively traverse all arguments and try and locate the `projectDir` property.
Skip, however, especially large objects like those starting with `$` (dependency-injected classes) or those ending with `service` (more dependency-injected classes) in order to prevent a maximum callstack exception.
Ping @rosen-vladimirov @PanayotCankov @sis0k0
=> Recursively look for projectDir when executing hooks

constants.ts, definitions/mobile.d.ts, helpers.ts, mobile/android/android-device-file-system.ts, mobile/android/android-device-hash-service.ts, test/unit-tests/helpers.ts
During running on Android, CLI tries to take smart decision which files to upload. This is done by checking the shasum of all project files and comparing it with the latest one uploaded to device. However, in huge projects, this leads to error with code EMFILE as the OS have limits for opened file handles.
This happens as CLI executes the operation simultaneously for all files. In order to fix this behavior, execute the actions by chunks (currently set to 100).
Introduce new method in helpers to execute this action and add tests for it.
Fixes https://github.com/NativeScript/nativescript-angular/issues/1079 and https://github.com/NativeScript/nativescript-cli/issues/3268
=> Fix EMFILE error when running on Android

services/project-files-manager.ts
On some systems with slower hard drives and rigorous antivirus software, on numerous occasions the newly created files in `platforms` directory are locked and cannot be renamed. The rename fails with `EPERM`.
Switching to write+delete in favor of rename eliminates said issue.
ping @rosen-vladimirov @KristianDD
=> Replace rename with write+delete

declarations.d.ts, helpers.ts, sys-info-base.ts, test/unit-tests/helpers.ts, test/unit-tests/sys-info-base.ts
The command `javac -version` prints result to stderr when JAVA 8 is used and to stdout when JAVA 9 is used. Current check in CLI uses the stderr output, so when JAVA 9 is installed it fails to detect the correct version.
In order to support both JAVA 8 and JAVA 9, capture both stdout and stderr and get the version from there.
Also remove unneeded check for Java version - we care about JAVA Compiler, which is included in JDK.
=> Fix detection of Javac version

http-client.ts
In some cases, when any of the requests fail, the response is not JSON (the servers do not respect the Accept header of the request) and return html.
In this case the JSON.parse operation that we execute in order to find the real error, is failing and we return error that we are unable to parse the result.
This leads to confusion in many cases, so return the real response of the server instead. So when html is returned, it will be included in the error.
This will help the users when they have some firewall issues and they are unable to connect to our servers. In this case they almost always receive html in which it is stated that this page is forbidded and they should contact their admins.
=> Return correct error when response is not JSON

declarations.d.ts, helpers.ts, http-client.ts, progress-indicator.ts
Add `getSpinner` method to `$progressIndicator` - it will return a new instance of clui.Spinner in case terminal is interactive. In case it is not - a mocked instance will be returned.
This way in CI builds the spinner will not print tons of repeated messages.
=> Add getSpinner method to $progressIndicator

definitions/mobile.d.ts, mobile/ios/simulator/ios-emulator-services.ts
Introduce new method - connectToPort to iOSEmulatorServices. This method will try to connect to specified port on users machine (typically this port will be used by NativeScript applications runnin on iOS Simulator) for a specified amount of time. In case it succeeds, the socket of the connection is returned. In case it fails, undefined is returned.
=> Introduce connectToPort method to iOSEmulatorServices

declarations.d.ts, os-info.ts, services/net-service.ts, test/unit-tests/services/net-service.ts
Add method in net service to check if port is in LISTEN state. Add tests for it.
The method has different implementation for macOS, Linux and Windows - added tests for each of the implementations.
=> feat(net): Add method to check if port is in LISTEN state

definitions/extensibility.d.ts, docs/helpers/basic-extensions-page.html, services/help-service.ts, test/unit-tests/services/help-service.ts
Each CLI extension may add new commands to CLI. Allow showing command help for these commands in case:
1. Commmand execution fails.
2. Users need more information for command - `tns <command> --help`
3. Users need full html help for command - `tns help <command>`.
Each extension that wants to use this functionality will have to add `nativescript` key in its `package.json` and add `docs` key in it. The `docs` key must point to the directory where the help content (.md files) is located, relative to the root directory of the extension.
When CLI needs to show command line help for extension's command, it will search the docs directories of all extensions.
When CLI needs to show HTML help for the extension's commands, it will generate `html` directory right next to the docs dir in the …
=> feat(extensions): Allow generation of help content for extension commands

helpers.ts
Instead of executing the first hook which tries to replace one of CLI's methods, execute them all in succession.
Pass the a reference to the original CLI method to the first hook, then a reference to the first hook's function to the second and so on.
This approach is inspired by objective-C's method swizzling and serves as a similar mechanism. Hooks should decide wether to call the original method or not.
Ping @rosen-vladimirov @KristianDD
=> feat(livesync): execute all hooks

declarations.d.ts, services/analytics/google-analytics-custom-dimensions.d.ts, services/commands-service.ts
We need to track users that export their projects from playground and opens them in CLI or Sidekick. To support that we introduce playground key in nativescript key in package.json file. For example:
```
{
"nativescript": {
"playground": {
"id": "some user quid",
"usedTutorial": false // is not obligatory. In case it is present, can be true or false
}
}
}
```
In  case when package.json file contains playground key, {N} CLI reads playground data and saves it in userSettings file. If usedTutorial=true is already saved in userSettings file, {N} CLI does not overwrite it. After that {N} CLI deletes playground key from package.json file.
In case when package.json file does not contain playground key, {N} CLI checks if playground key is already saved in userSettings file. If this is the case, …
=> feat(Analytics): Respect playground key from package.json file

commands/help.ts, constants.ts, declarations.d.ts, definitions/commands-service.d.ts, definitions/extensibility.d.ts, helpers.ts, services/commands-service.ts, services/help-service.ts, test/unit-tests/services/help-service.ts
In case user executes any command that is registered in extension, but this extension is not installed, they'll receive error:
`Unknown command ...`. Instead of showing this, it is better to tell them how to get access to this command.
In order to achieve this, implement a new logic in `extensibilityService` to find commands registered in all extensions. CLI searches npm (via npms API) for packages that have the keyword `nativescript:extension`.
After that, CLI gets the package.json of the latest version of each dependency (via registry.npmjs.org) and searches for nativescript key in it. In case it has nativescript key, CLI reads the commands value inside it. The value should be string array containg all commands registered in extension's bootstrap.
When user writes down a command that is …
=> feat(extensibility): Add hint how to get access to a command from extension

appbuilder/providers/appbuilder-livesync-provider-base.ts, definitions/mobile.d.ts, mobile/android/android-device-file-system.ts, mobile/ios/device/ios-device-file-system.ts, mobile/ios/simulator/ios-simulator-file-system.ts
Return the actual files transferred to the device instead of `void`.
=> refactor: change transferfiles return type

declarations.d.ts, definitions/commands-service.d.ts, errors.ts, services/commands-service.ts
When build or run command is executed, checks if the environment is properly configured for executing local builds. If it is not properly configured, {N} CLI shows a prompt and user is able to choice if to run setup script or use cloud builds.
If cloud builds option is selected, {N} CLI installs the nativescript-cloud extension and prints that user can use the $ tns login command to log in with his/her account and then $ tns cloud run/build android/ios command to build his/her app in the cloud.
If setup script option is selected, {N} CLI runs the setup script to try and automatically configure the environment. If the environment is not properly configured after executing the setup script, {N} CLI shows a prompt and user is able to choice if to use cloud builds or manually setup the …
=> Getting started improvements

services/user-settings-service.ts
In case when user executes some command and by some reasons user settings file is not a valid json, {N} CLI throws "Unexpected token in JSON at position 0" error. After that user is not able to execute any cli command until the file exists.
https://github.com/NativeScript/nativescript-cli/issues/3151
=> fix(userSettings): Don't fail when user settings file is not a valid json

README.md, appbuilder/device-log-provider.ts, appbuilder/services/livesync/ios-livesync-service.ts, commands/device/run-application.ts, commands/device/stop-application.ts, definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/android/android-log-filter.ts, mobile/application-manager-base.ts, mobile/device-log-provider-base.ts, mobile/device-log-provider.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/ios-log-filter.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/log-filter.ts, mobile/mobile-core/devices-service.ts, services/livesync-service-base.ts, test/unit-tests/android-application-manager.ts, test/unit-tests/android-log-filter.ts, test/unit-tests/appbuilder/device-log-provider.ts, test/unit-tests/ios-log-filter.ts, test/unit-tests/log-filter.ts, test/unit-tests/mobile/application-manager-base.ts, test/unit-tests/mobile/devices-service.ts
When strating iOS Application, set the projectName to the log filter, so
we can filter the logs by it. Same logic is used for Android, where we
are using the PID of the started application. So introduce
IDeviceLogOptions, where logLevel, pid and projectName can be set. Pass
the projectName wherever is required in order to get it in
startApplication.
In order to make future refactorings easier, introduce a single object as an argument to some of the methods in devices' ApplicationManagers.
=> refactor: Set logFilter's project name when starting iOS application 

constants.ts, test/unit-tests/yok.ts, yok.ts
In case a command like `sample|command|*default` is registered CLI should be able to correctly execute 
`tns sample command`
Added tests to ensure functionality
Ping @rosen-vladimirov @Fatme
=> refactor: allow multipart default commands

test/unit-tests/yok.ts, yok.ts
Includes:
* Remove logic from `getDefaultCommand` that modifies the input arguments
* Enable `buildHierarchicalCommand` to find default commands
* Fix tests accordingly
Fixes the issue where commands that are hierarchical, however consist of multiple parts are not recognized.
Ping @Fatme @rosen-vladimirov
=> fix: find correct hierarchal commands

declarations.d.ts
Currently when doctor command is executed, NativeScript components versions information is displayed as table. With this PR NativeScript components versions will be displayed with terminal spinners.
In case when component is up to date with latest available version, success spinner will be displayed.
In case when for component update is available, warn spinner will be displayed.
In case when component is not installed, fail spinner will be displayed.
This PR changes also the behaviour of `tns info` command. When `tns info` command is executed,  NativeScript components versions information also will be displayed with terminal spinners.
=> Add spinner when checking for NativeScript components versions

commands/post-install.ts, definitions/commands.d.ts, services/commands-service.ts
Introduce postCommandAction that is executed when command succeeds. This action should be used to print additional information to users how to continue after this command.
=> feat(commands): Introduce postCommandAction

definitions/mobile.d.ts, mobile/android/android-application-manager.ts, mobile/application-manager-base.ts, mobile/ios/device/ios-application-manager.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, services/livesync-service-base.ts, test/unit-tests/mobile/application-manager-base.ts, test/unit-tests/mobile/devices-service.ts
When the public method `devicesService.deployOnDevices` is used, the device logs for iOS are not shown. The problem is that the method calls `canStartApplication`, which returns false on Windows.
Remove the check and also ensure the set of projectName for the deviceLogProvider will be called no matter of the way we start iOS Applications (through the mounted image or through Safari on device).
Remove `canStartApplication` method from application managers as it does not have a useful usage. Previously we've used it on Windows and Linux as we did not have a way to start iOS applications.
Now, as we have implemented such way through Safari, the method has lost its purpose.
=>  fix(deviceLogs): iOS device logs are not shown when deployOnDevices is used

mobile/ios/device/ios-application-manager.ts
When cloud build is used and iOS device does not have Developer Disk Image mounted, the logs are not visible. The problem is that the code fails to start/stop the application before starting the device log streams.
Fix this by starting the logs before trying to start/stop the application.
=> fix(logs): Logs from iOS device are not shown on Windows

mobile/ios/simulator/ios-simulator-log-provider.ts
In case when more than one simulator is running, logs are shown only from one of them.
Also fixes the behaviour when simulator's log process is interrupted in case when cli is used as library.
=> fix (ios-simulator): Show logs from all running iOS simulators

bootstrap.ts, mobile/mobile-core/android-process-service.ts
Expose the `getAppProcessId` method from `androidProcessService`, so it can be called when using CLI as a library.
Remove unused property from the class.
=> feat(API): Expose androidProcessService - getAppProcessId

mobile/mobile-core/ios-simulator-discovery.ts
In case when some configuration problem occurs on the machine, Sidekick hangs on splashscreen because unhandled exception is thrown.
Should be merged with this PR: https://github.com/telerik/ios-sim-portable/pull/105
=> Fix unhandled exception that is thrown in case when there are a configuration problem on the machine

definitions/mobile.d.ts, mobile/mobile-core/android-process-service.ts
Introduce new method for Android port forwarding in the android-process-service. This method is based on already existing ones, but it skips several checks that are not valid for the current case.
Also fix the removing of the port forward when multiple Android devices/emulators are attached - the current command does not work in this case as it does not specify `-s <device>`. Fix this by persisting the information for forwarded ports and devices
=> feat: Introduce method for Android port forwarding

commands/doctor.ts, declarations.d.ts, package.json
Update calls to `nativescript-doctor` package to pass projectDir where applicable. This allows the package to verify installed Java Compiler version against the project's Android runtime.
This is required in case the installed Java version is 10 or above and the Androud runtime in the project is older than 4.1.0. In this case the user cannot build this application for Android, but have to update the Android runtime version or downgrade the Java version.
=>  feat: Validate Java compiler version based on runtime version

definitions/mobile.d.ts, mobile/ios/simulator/ios-emulator-services.ts
The current logic for launching application on specific iOS Simulator reads the device from the `$options` option. This does not work in many cases (for example `tns debug ios` when multiple simulators are running and CLI prompts you to select one.
So add option in the emulator options to specify device and read it from there.
=> fix: Unable to launch application on specific iOS Simulator

declarations.d.ts, package.json
Add logic to validate environment based on the specified runtime version. This is required for the cases where the runtime version is not specified in the project's package.json but we need to verify if a runtime version can be used
Depends on: https://github.com/NativeScript/nativescript-doctor/pull/37
=>  fix: Validate environment based on specified runtime version  

appbuilder/providers/device-app-data-provider.ts, definitions/mobile.d.ts, mobile/ios/simulator/ios-simulator-application-manager.ts, mobile/ios/simulator/ios-simulator-device.ts, mobile/ios/simulator/ios-simulator-log-provider.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/3545
Should be merged after this PR:
https://github.com/telerik/ios-sim-portable/pull/106
=> Use async API from ios-sim

file-system.ts
related to [issue #3741]( https://github.com/NativeScript/nativescript-cli/issues/3741)
=> fix: fix file not found exception when enumerating a dir with non existing symlinks 

declarations.d.ts, definitions/mobile.d.ts, mobile/mobile-core/devices-service.ts, mobile/mobile-core/ios-device-discovery.ts, test/unit-tests/mobile/devices-service.ts
Speed up device detection by:
* removing duplicate calls to all device detection services
* cache the Promise of initialize method - this way even when multiple calls are executed simultaneously, the result of the first one will be used. This allows Sidekick to call the method asynchronously.
* do not execute iOS device detection in case `--emulator` is passed
Remove several public methods from the service - make them protected as we already have tests for them.
Remove all calls to detectCurrentlyAttachedDevices method outside of the service - the initialize method will do it anyway, so no need to call it externally.
Remove duplicate calls in the startLookingForDevices method - previously it had to filter which device detection services to call. As now each device detection service checks …
=> feat: Speed up device detection

mobile/android/android-emulator-services.ts
Fix the message to be consistent with the one here:  https://github.com/telerik/ios-sim-portable/blob/a8740c16eef3fe7e75a0e5950a2bc65cfeb77994/lib/iphone-simulator-xcode-simctl.ts#L253
=> Fix the message for missing android emulator to be consistent with iOS

mobile/mobile-core/ios-simulator-discovery.ts
We don't check what is the operating system before executing shell commands for detecting running iOS simulators.
=> fix: checking for iOS simulators on windows

appbuilder/device-emitter.ts, commands/device/list-devices.ts, constants.ts, definitions/mobile.d.ts, mobile/android/android-emulator-services.ts, mobile/android/android-virtual-device-service.ts, mobile/android/genymotion/genymotion-service.ts, mobile/emulator-helper.ts, mobile/ios/simulator/ios-emulator-services.ts, mobile/mobile-core/android-emulator-discovery.ts, mobile/mobile-core/devices-service.ts, mobile/mobile-core/ios-simulator-discovery.ts, mobile/wp8/wp8-emulator-services.ts, test/unit-tests/mobile/android-emulator-service.ts, test/unit-tests/mobile/android-virtual-device-service.ts, test/unit-tests/mobile/genymotion/genymotion-service.ts
Rename `getAvailableEmulators` to `getEmulatorImages` as we return information for all emulator images - running and not.
Rename the events `emulatorImagesFound` and `emulatorImagesLost` to `emulatorImageFound` and `emulatorImageLost` as emitted data contains a single emulator image.
=> chore: Rename exposed methods and events for emulators

definitions/mobile.d.ts, mobile/android/android-debug-bridge.ts, mobile/android/android-emulator-services.ts, mobile/android/android-virtual-device-service.ts, mobile/android/genymotion/genymotion-service.ts, mobile/mobile-core/android-device-discovery.ts, test/unit-tests/mobile/android-debug-bridge.ts, test/unit-tests/mobile/android-emulator-service.ts, test/unit-tests/mobile/android-virtual-device-service.ts
`tns run android` command fails when there are no Android emulators available. The problem is that the output of `avdmanager list avds` is incorrectly parsed by CLI and it fails (output is `Available Android Virtual Devices:\n`).
Fix this by improving the parsing logic.
Also fix incorrect checks for executables on Windows - the files have `.bat` extension, which was not added, so the check if the file exist was failing.
Unify the calls to `adb devices` - curently there are two implementations on different places in the code - unify them and add a new method that does not fail in case `adb devices` command fails. The new method is usable when we want to list currently available simulators/emulators.
=> fix: `tns run android` command fails when no emulators are available

constants.ts, definitions/mobile.d.ts, mobile/android/android-virtual-device-service.ts, mobile/ios/simulator/ios-emulator-services.ts, mobile/ios/simulator/ios-simulator-device.ts, test/unit-tests/mobile/android-emulator-service.ts, test/unit-tests/mobile/android-virtual-device-service.ts, test/unit-tests/mobile/genymotion/genymotion-service.ts, test/unit-tests/mobile/ios-simulator-discovery.ts
Whenever CLI returns information for available emulators/simulators, the returned object for each of the image has a status property.
For Android the status is "Running" or "Not running", for iOS it is "Connected" or "Disconnected".
Unify the status properties - use "Running" and "Not running" for both of the images.
Also, for iOS images, the imageIdentifier property has not been populated - fill it with the value of the identifier property, so the API will be consistent for both Android and iOS.
As the property has not been populated for iOS Simulators, the events "emulatorImageFound" and "emulatorImageLost" were never triggered in case you add new iOS Simulator images. Now this should work correctly.
Fix unit tests on Windows - the split by EOL when parsing the output of avdmanager …
=> fix: status of iOS Sim images and Android Emulator images are different

constants.ts, mobile/android/genymotion/genymotion-service.ts, test/unit-tests/mobile/genymotion/genymotion-service.ts
In previous versions of Genymotion, trying to execute the `player` command fails with exit code 1, without real error. In order to handle this case, do not fail in case there's nothing on the stderr (or the process errors really bad).
In recent versions of Genymotion, the stderr contains a string that for Logging activities to file even when the command succeeds. So we have ignored this error for the moment.
Improve the message when there's an error.
=> fix: error is shown for Genymotion emulators with old Geny player

declarations.d.ts
Extract the proxy setting to a new interface, so it can be reused.
=> chore: extract proxy setting to new interface

mobile/android/android-device-hash-service.ts
Comparing the old shasums and new shasums takes a lot of time as we use find for searching in a map. Instead, just check if we have the entry we are looking for.
In bigger projects (for example with more than 20 000 files including node_modules), the comparison may take more than 100 seconds, which breaks the LiveSync for Android as the socket is closed after 70 seconds without action.
So, in case you have a huge project and try `tns run android`, you'll probably receive:
```
Unable to apply changes on device: 192.168.3.101:5555. Error is: Socket Error:
Error: write ECONNABORTED.
```
After the change, the time for comparing 24 000 shasums is 25 ms instead of more than 100 seconds
=> fix: comparing shasums takes a lot of time

mobile/android/android-debug-bridge.ts
On Windows machines we were sending Windows style paths to `adb mkdir` which resulted in `Read-only file system` error from `adb`. The reason for that behavior is that when executed on Windows machines `path normalize` uses the Windows style path separator.
=> fix: android livesync to Android P devices on Windows machines

mobile/android/android-virtual-device-service.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/mobile/android-virtual-device-service.ts, test/unit-tests/mobile/devices-service.ts
Whenever androidEmulatorDiscovery raises `emulatorImageFound` or `emulatorImageLost` event, an error is raised in the code as `devicesService` expects to receive an array, but it receives a single image instead.
Fix the code in devicesService to handle correctly the event. Also add logic to handle the same events from iOSSimulatorDiscovery.
In case the Android Emulator image does not have displayName set in the config.ini file, the displayName that CLI sets fallbacks to `hw.device.name` property.
However, this name is not the one that is visible in other tools, like Android Studio for example. As a user I expect to see the same name as in Android Studio.
In order to fix this, fallback to the AvdId value from config.ini file and if it is missing, fallback to `hw.device.name`.
Here's an …
=> fix: emulator API fixes

declarations.d.ts, definitions/commands.d.ts, mobile/mobile-core/devices-service.ts, services/commands-service.ts
Implements: https://github.com/NativeScript/nativescript-cli/issues/3813
Should be merged with this: https://github.com/NativeScript/nativescript-cli/pull/3853
=> Playground

definitions/mobile.d.ts, mobile/android/android-debug-bridge.ts, mobile/android/android-device-file-system.ts, mobile/android/android-device-hash-service.ts, mobile/ios/device/ios-device-file-system.ts, mobile/ios/simulator/ios-simulator-file-system.ts, test/unit-tests/mobile/android-device-file-system.ts
`tns run android` command transfers all files on initial sync. Actually there is no need to transfer all files on device because the installed `.apk` contains them. So after the application is installed on device, calculate the hashes for files inside `\plaforms\android\app\*` and upload the hash file on device. When the initial sync is executed {N} CLI compares the hashes and no file is transferred on device because all files are the same (no change is occurred). This PR speeds up the initial livesync with around 15seconds for angular application.
=> Speed up android livesync

services/hooks-service.ts
Currently `hooksService` is initialized with the following directories:
```
<path-to-cli>/lib/hooks
<path-to-cli>/lib/common/hooks
```
Actually this directories do not exist and no need to iterate them.
This fix should speed up the hooks execution.
=> fix: don't execute hooks for directories that do not exist

helpers.ts, mobile/mobile-core/devices-service.ts, test/unit-tests/helpers.ts, test/unit-tests/mobile/devices-service.ts
In case the device identifier contains only numeric symbols or in case it looks like a number (16089e09 for example), CLI fails to work with it.
The problem is that CLI thinks an index is passed to it, so it removes "one" from the passed number and tries to find the device on the new index.
The other issue is with the `isNumber` helper method which works incorrectly when the string looks like number. Improve the logic in the method and rename it. We cannot parse safely values with exponent (`1e6` for example), but we do not need such functionality.
The new method name and tests reflects the described behavior.
=> fix: unable to work with devices with numeric identifiers
