- mobile/android/android-emulator-services.ts
Implements http://teampulse.telerik.com/view#item/280977
> Allow emulate android command to wait forever using --timeout 0

- mobile/android/android-emulator-services.ts
Add unlock of avd image after installation is completed for cases when it takes a lot of time. This way the application will be loaded immediately. Without this code, the user has to unlock the device manually and after that the launch will start.
http://teampulse.telerik.com/view#item/280997
> Unlock avd after app installation

- mobile/app-identifier.ts
- mobile/mobile-helper.ts
See http://teampulse.telerik.com/view#item/262237
> Support for WP8 Ion

- declarations.d.ts
- definitions/mobile.d.ts
- mobile/android/android-emulator-services.ts
- mobile/ios/ios-emulator-services.ts
- mobile/wp8/wp8-emulator-services.ts
Also, gives a proper message to the user
Implements http://teampulse.telerik.com/view#item/279833
> Android Emulator now checks whether the SDK is correctly configured

- options.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/172
> Share appid option

- definitions/mobile.d.ts
- mobile/android/android-device.ts
- mobile/app-identifier.ts
- mobile/ios/ios-device.ts
* Pass liveSyncUrl as param to sync function instead projectType
* Remove getLiveSyncUrl function
http://teampulse.telerik.com/view#item/283024
> Refactor project class

- helpers.ts
- options.ts
Add new function to helpers.ts which prints a message on the same line (using printInfoMessageOnSameLine method from the same helpers.ts) after a specific timeout had passed. Using future to guarantee that the function will not finish until timeout is passed and message is printed.
This function is needed when building project in order to show some kind of a progress (in this case Building........) when executing long operation. This way the users will know something is still working there.
http://teampulse.telerik.com/view#item/278000
> Add function to print message after timeout

- bootstrap.ts
- commands/post-install.ts
refs https://github.com/NativeScript/nativescript-cli/issues/171
> Share the dev-postinstall command between the CLIs

- file-system.ts
See http://teampulse.telerik.com/view#item/282660
> FileSystem.writeJson defaults to a TAB character for pretty-printing

- yok.ts
See http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx for the goodies
> Update to TypeScript 1.4

- definitions/config.d.ts
- http-client.ts
> Export Fiddler HOSTNAME to config.json

- declarations.d.ts
- file-system.ts
Add method to unzip specific files only. This way you can extract only some files (based on the filter) from any zip archive.
http://teampulse.telerik.com/view#item/284263
> Unzip specific files

- bootstrap.ts
- commands/device/device-log-stream.ts
- commands/device/list-applications.ts
- commands/device/list-devices.ts
- commands/device/run-application.ts
- definitions/mobile.d.ts
- mobile/ios/ios-core.ts
- mobile/ios/ios-device.ts
- mobile/ios/ios-proxy-services.ts
- mobile/mobile-core/devices-services.ts
http://teampulse.telerik.com/view#item/283764
> Run application on iOS device on OSX

- bootstrap.ts
http://teampulse.telerik.com/view#item/284568
> Add removed post-install command

- bootstrap.ts
- definitions/mobile.d.ts
- definitions/open.d.ts
- helpers.ts
- mobile/android/android-device.ts
- mobile/ios/ios-device.ts
- opener.ts
- options.ts
- services/commands-service.ts
see https://github.com/NativeScript/nativescript-cli/pull/193
ping @teobugslayer @Fatme
> Implement debug command

- commands/post-install.ts
See http://teampulse.telerik.com/view#item/284635
> Chmod FTW!

- child-process.ts
- mobile/android/android-emulator-services.ts
Fix error handling on process spawn
Fixes http://teampulse.telerik.com/view#item/279833
> Fix checking for Android SDK

- definitions/mobile.d.ts
- mobile/ios/ios-core.ts
Fixing deploy on ios device on windows OS
> Don't try to convert the message if the format used for communication is xml

- commands/device/list-applications.ts
- definitions/bplist-parser.ts
- definitions/mobile.d.ts
- mobile/android/android-device.ts
- mobile/ios/ios-core.ts
- mobile/ios/ios-device.ts
Fixing the issues from this story http://teampulse.telerik.com/view#item/283764
> Fix run command

- mobile/ios/ios-core.ts
- validators/iTunes-validator.ts
http://teampulse.telerik.com/view#item/285187
http://teampulse.telerik.com/view#item/285576
> Support for ios releated commands and iTunes x64

- mobile/ios/ios-core.ts
With iTunes x64 the signature of AFCFileRefOpen was changed
> Fix AFCFileRerfOpen signature

- declarations.d.ts
- file-system.ts
Related to http://teampulse.telerik.com/view#item/285465
7zip is case-sensitive by default
> Add option for case-insensitive unzip for 7zip

- mobile/mobile-core/device-discovery.ts
Merge release in master (for 2.8.1)
> Merge release in master (for 2.8.1)

- mobile/android/android-emulator-services.ts
Merge release branch (used by nativescript-cli) in master branch.
> Merge release branch in master

- declarations.d.ts
- definitions/node.d.ts
- definitions/progress-stream.d.ts
- definitions/unzip.d.ts
- helpers.ts
- http-client.ts
- mobile/android/android-device.ts
- mobile/ios/ios-core.ts
- mobile/ios/ios-device.ts
- services/cancellation.ts
> Update .d.ts for Node 0.12

- services/analytics-service.ts
Set userAgentString to (osType). For example on Linux the agent will be (Linux).
> Fix analytics OS tracking

- config-base.ts
- definitions/config.d.ts
- http-client.ts
- services/analytics-service.ts
Merge release branch for NativeScript 0.9.2
> Merge release branch for NativeScript 0.9.2

- bootstrap.ts
- commands/post-install.ts
- declarations.d.ts
- definitions/log4js.d.ts
- definitions/logger.d.ts
- definitions/osenv.d.ts
- dispatchers.ts
- file-system.ts
- host-info.ts
- logger.ts
- sysinfo.ts
Gather system information about the runtime environment.
> Emit system information on every run of the CLI

- sysinfo.ts
The issue is that `android -h` returns exit code 1, which is unconventional and inconvenient way of working for a unix command-line tool
> Fix warning for missing androis sdk on mac

- commands/device/run-application.ts
- definitions/config.d.ts
- errors.ts
- helpers.ts
- mobile/ios/ios-device.ts
- mobile/mobile-core/device-discovery.ts
- mobile/mobile-core/devices-services.ts
- services/commands-service.ts
Add mechanism to disable hooks and analytics.
> Disable hooks and analytics

- bootstrap.ts
- commands/device/get-file.ts
- commands/device/list-files.ts
- commands/device/put-file.ts
- commands/device/uninstall-application.ts
- definitions/mobile.d.ts
- mobile/android/android-device.ts
- mobile/ios/ios-core.ts
- mobile/ios/ios-device.ts
- mobile/ios/ios-proxy-services.ts
Implements http://teampulse.telerik.com/view#item/258070
> iDeviceTester commands

- errors.ts
Remove incorrect console.log which was used only for debug.
> Remove incorrect console.log

- commands/post-install.ts
- declarations.d.ts
- sysinfo.ts
The release counterpart to https://github.com/telerik/mobile-cli-lib/pull/273
> Add check and warning for missing java during installation

- mobile/wp8/wp8-emulator-services.ts
Fixes http://teampulse.telerik.com/view#item/289843
> Pick the correct 32-bit Program Files directory regardless node bitness

- docs/helpers/basic-page.html
- services/html-help-service.ts
The following improvements are included:
* Make the logo of the CLI in HTML Help a link to index.html page.
* In console help replace `&nbsp;` with space.
* In console help replace all links with their text.
* In console help remove the inner borders of cli-tables.
> Improve help service

- mobile/ios/ios-device.ts
http://teampulse.telerik.com/view#item/290037
> Bring back livesync for iOS 8.3 

- definitions/minimatch.d.ts
- helpers.ts
- mobile/android/android-device.ts
Merge release in master (for 0.10.0)
> Merge release in master (for 0.10.0)

- services/analytics-service.ts
Report node version to Analytics
To see the numbers, switch to the icenium-cli project insde platform analytics workspace and navigate to Feature Reports -> Feature Use -> NodeJSVersion.
Due to issues in used analytics sdk, several hacks must be made, marked with HACK comment.
The version is reported with underscores instead of points, again due to sdk limitation.
Implements http://teampulse.telerik.com/view#item/290451
> Report node version to analytics

- definitions/mobile.d.ts
- mobile/ios/ios-proxy-services.ts
http://teampulse.telerik.com/view#item/290210
> Fix wrong message when livesyncing and remove unneeded function

- definitions/commands-service.d.ts
- services/commands-service.ts
http://teampulse.telerik.com/view#item/290527
> Enable autocompletion for dynamic commands

- commands/preuninstall.ts
- docs/helpers/styles.css
> Fix message on preuninstall

- services/auto-completion-service.ts
When we check if autocompletion or obsolete autocompletion is enabled, in case one of the shell scripts (.bash_profile for example) is missing, ENOENT error is raised. Catch it and just log it with trace option.
Fixes http://teampulse.telerik.com/view#item/290688
> Fix ENOENT error in autocompletion service

- services/commands-service.ts
Fixes http://teampulse.telerik.com/view#item/290977
> Fixes validation of hierarchical commands with too many arguments

- commands/preuninstall.ts
- declarations.d.ts
- definitions/commands-service.d.ts
- definitions/mobile.d.ts
- definitions/options-service.d.ts
- docs/helpers/styles.css
- mobile/ios/ios-proxy-services.ts
- services/auto-completion-service.ts
- services/commands-service.ts
- services/html-help-service.ts
- services/typescript-compilation-service.ts
- yok.ts
Merge release-appbuilder branch after 2.9.0
> Merge release-appbuilder branch after 2.9.0

- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
This is the respective missing commit in `lib/common` of https://github.com/NativeScript/nativescript-cli/pull/423
> Switch the debugging on emulator for iOS to use the iOSEmulatorService

- logger.ts
So that they are not outputted when --log trace option is provided
Fixes http://teampulse.telerik.com/view#item/289692
> Encode passwords with asterisks

- definitions/commands.d.ts
- definitions/config.d.ts
- services/commands-service.ts
Merge appbuilder's 2.9.1 in master
> Merge appbuilder's 2.9.1 in master

- file-system.ts
Fixes http://teampulse.telerik.com/view#item/291262
> Rollback properly upon cordova migration failure

- mobile/ios/ios-emulator-services.ts
Conflicts:
mobile/ios/ios-emulator-services.ts
project-helper.ts
> Merge 1.0.1 release in master

- commands/post-install.ts
- declarations.d.ts
- sysinfo.ts
At install, warn if there is problem with mono installation
Implements http://teampulse.telerik.com/view#item/291901
> Detect mono version

- validators/iTunes-validator.ts
http://teampulse.telerik.com/view#item/292423
> Fix iTunes validator on windows

- mobile/android/android-emulator-services.ts
Also, fix broken support for preview SDKs
See https://github.com/NativeScript/nativescript-cli/issues/507
> Support for Android MNC in emulator

- services/cancellation.ts
Merge pre 2.10 release-appbuilder in master
> Merge pre 2.10 release-appbuilder in master

- mobile/ios/ios-emulator-services.ts
Fixes http://teampulse.telerik.com/view#item/293581
> Fix emulate command

- declarations.d.ts
See https://github.com/NativeScript/nativescript-cli/issues/480 and http://teampulse.telerik.com/view#item/294290
> Implement doctor command in AppBuilder CLI

- definitions/config.d.ts
- dispatchers.ts
- static-config-base.ts
> Merge 2.10.1 in master

- file-system.ts
- helpers.ts
* Replace BOM from the header of the file if it exists
* Throw in prompter if console isn't interactive
* Introduce trimSymbol function
> Mobile-cli modifications

- declarations.d.ts
- sysinfo.ts
required for http://teampulse.telerik.com/view#item/296931
> Detect Git version

- mobile/android/android-device-file-system.ts
On some devices  adb push removes write permission of others group. This is problem when trying to move files to /data/data because run-as is always executed with different user from the user who pushes the files to /data/local/tmp.
Fixes https://github.com/NativeScript/nativescript-cli/issues/654
> Ensure that all directories have permissions

- commands/device/stop-application.ts
- mobile/ios/ios-application-manager.ts
Fixes https://github.com/telerik/mobile-cli-lib
Fixes the second part of this issue https://github.com/NativeScript/nativescript-cli/issues/654
> Fix livesync ios when having both iOS and Android devices connected at the same time

- declarations.d.ts
- definitions/mobile.d.ts
- mobile/device-app-data/device-app-data-factory.ts
- mobile/ios/ios-device-file-system.ts
- services/usb-livesync-service-base.ts
Fixes http://teampulse.telerik.com/view#item/297546
> Apply livesync refactoring to app-cli

- declarations.d.ts
- file-system.ts
The getFileShasum method must return the shasum of a provided file.
> Add getFileShasum method

- dispatchers.ts
> Merge onpremise in master

- services/usb-livesync-service-base.ts
http://teampulse.telerik.com/view#item/298483
> Fix livesync --watch command

- declarations.d.ts
- services/usb-livesync-service-base.ts
https://github.com/NativeScript/nativescript-cli/issues/742
> Integrate livesync logic from android runtime

- definitions/mobile.d.ts
- mobile/android/android-debug-bridge.ts
Get all adb output, even for large operations
Fixes https://github.com/NativeScript/nativescript-cli/issues/730
> Speed up adb start

- commands/help.ts
- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
- options.ts
Fix bad command line - "--timeout null"
Fix bad command line - lunching from Graphite
Use ES6 imports
> Refactor remote command

- child-process.ts
- definitions/mobile.d.ts
- logger.ts
- mobile/android/android-application-manager.ts
- mobile/android/android-debug-bridge.ts
- mobile/android/android-device-file-system.ts
- mobile/android/android-device.ts
- mobile/android/android-livesync-service.ts
Generate proper command line for strating adb
Change public API for adb-related functions
Use ES6 imports
When there's no content in http body , print [no content] instead of [nothing]
Fixes http://teampulse.telerik.com/view#item/299038
> Fix android device-related commands

- mobile/android/android-debug-bridge.ts
See http://teampulse.telerik.com/view#item/299038
> Fixes for android related commands

- declarations.d.ts
- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
- services/usb-livesync-service-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/776
> Fix livesync ios --emulator --watch if the file is not at project root level

- errors.ts
This reverts commit 3c364d538e437dc677cfda111da78c51f2bea4e5 which was for master branch, not for here.
> Revert "Write error to stderr"

- child-process.ts
- declarations.d.ts
- sysinfo.ts
Introduce a flag to show output from stderr
Add javac and gradle detection.
> Show stderr in childProcess.exec

- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/android/android-device.ts
- mobile/ios/ios-application-manager.ts
- mobile/ios/ios-device.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/896
> Fix run, livesync, run workflow

- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/android/android-device.ts
- mobile/ios/ios-application-manager.ts
- mobile/ios/ios-device.ts
- mobile/mobile-core/devices-services.ts
Cherry pick from release branch
Also, a small ES6 change
Required to fix http://teampulse.telerik.com/view#item/300909
> fix package def parsing

- services/usb-livesync-service-base.ts
Merge 1.3.0 in master
Conflicts:
services/usb-livesync-service-base.ts
> Merge 1.3.0 in master

- services/usb-livesync-service-base.ts
Legit - overriden in nativescript-cli
> Fix tslint error about empty method body.

- definitions/lodash.d.ts
- helpers.ts
`_.last()` is not defined correctly in lodash.d.ts, so it cannot be used in
chains. Add it (copy-paste the code from `_.first`).
> Add last as chainable in lodash.d.ts

- definitions/logger.d.ts
- logger.ts
Accept ...args rather than a single message
> Fix printMarkdown method parameters

- declarations.d.ts
- sysinfo.ts
https://github.com/NativeScript/nativescript-cli/issues/949
> Warning if pods are not installed and for old CocoaPods versions

- helpers.ts
Add method in helpers that can be used to append version with .0s, for
example 1.2 can become 1.2.0.
> Add method for appending version with .0s

- definitions/lodash.d.ts
- helpers.ts
> Merge 2.12.0

- definitions/mobile.d.ts
- mobile/android/android-emulator-services.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1031
> Fix emulate-livesync-emulate

- definitions/shelljs.d.ts
A minor d.ts change needed by the [NPM scope PR](https://github.com/NativeScript/nativescript-cli/pull/1068)
> Add the mkdir definition to shelljs.d.ts

- bootstrap.ts
- declarations.d.ts
- file-system.ts
- resource-loader.ts
- services/dynamic-help-service.ts
- services/usb-livesync-service-base.ts
Goes together with nativescript/nativescript-cli#1016
> Enhanced livesync support for the NativeScript unit test runner

- mobile/ios/ios-emulator-services.ts
See http://teampulse.telerik.com/view#item/300209
> Fix starting of iOS Simulator for AppBuilder CLI

- mobile/ios/ios-proxy-services.ts
required to fix http://teampulse.telerik.com/view#item/303345
> Remove delay before printing device log

- verify-node-version.ts
see http://teampulse.telerik.com/view#item/304396
> remove bad require

- bootstrap.ts
- declarations.d.ts
- helpers.ts
- package.json
- services/hooks-service.ts
- yok.ts
* hooks that have a 'module.exports = ...' statement are executed in-process and the exported function is injected
* global Promise polyfill
* hooked method arguments are injected into hooks through the 'hookArgs' argument
> in-process hooks with injector support

- commands/autocompletion.ts
- decorators.ts
- definitions/node-uuid-base.d.ts
- definitions/node-uuid-cjs.d.ts
- definitions/node-uuid.d.ts
- dispatchers.ts
- fiber-bootstrap.ts
- helpers.ts
- logger.ts
- mobile/android/android-device.ts
- mobile/ios/ios-application-manager.ts
- mobile/ios/ios-core.ts
- mobile/ios/ios-device-file-system.ts
- mobile/ios/ios-device.ts
- mobile/ios/ios-proxy-services.ts
- mobile/ios/ios-sys-log.ts
- mobile/mobile-core/devices-service.ts
- mobile/mobile-core/ios-device-discovery.ts
- mobile/mobile-helper.ts
- options.ts
- prompter.ts
- services/auto-completion-service.ts
- services/commands-service.ts
- test/unit-tests/decorators.ts
- validators/project-name-validator.ts
ES6 imports
Add definitions for node-uuid
> Fix ios devices code under Windows

- declarations.d.ts
- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
- services/usb-livesync-service-base.ts
Fixes  https://github.com/NativeScript/nativescript-cli/issues/1123
> Fix first `tns livesync ios --emulator`

- declarations.d.ts
- services/usb-livesync-service-base.ts
> Always restart upon livesync

- helpers.ts
Quote strings to be usable on command line
> Add quoteString

- mobile/android/android-device.ts
Get back the message that reports successful deploy on android device. We've deleted it a couple of commits ago.
> Show message after successful deploy

- .vscode/settings.json
- appbuilder/device-emitter.ts
- appbuilder/proton-bootstrap.ts
- messages/messages.ts
- mobile/mobile-core/android-device-discovery.ts
- package.json
Made Proton buildable with latest common lib
> Fixed device detection in Proton

- definitions/shelljs.d.ts
Update shelljs definitions to latest one from DefinitelyTyped.
> Update shelljs definitions

- mobile/android/android-application-manager.ts
https://github.com/NativeScript/nativescript-cli/issues/1130
> Show application output from livesync command

- definitions/shelljs.d.ts
- mobile/android/android-application-manager.ts
Merge release in  master pre 1.5.0 (third time)
> Merge release in  master pre 1.5.0 (third time)

- declarations.d.ts
- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
- services/usb-livesync-service-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1225
> Fix livesync --emulator when the app is not installed on the iOS simulator

- services/usb-livesync-service-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1234
> Fix livesync of platform specific files on iOS simulator

- helpers.ts
- test/unit-tests/sys-info-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1242
> Fix "ANDROID_HOME environment variable is not set correctly"  error

- definitions/mobile.d.ts
- mobile/android/android-device-file-system.ts
- mobile/android/android-livesync-service.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1246
> Fix ENAMETOOLONG on windows

- definitions/moment.d.ts
- services/usb-livesync-service-base.ts
See https://github.com/NativeScript/nativescript-cli/issues/1263
> Livesync operations are timestamped

- services/usb-livesync-service-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1210
> Fix devices service not initialized

- services/hooks-service.ts
When any of the hooks fail, we show help of the command.
Hooks failure is not bad user input, so we should not show help.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1268
> Do not show help when hook fails

- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/ios/ios-application-manager.ts
Merge release-appbuilder in master
> Merge release-appbuilder in master

- package.json
- static-config-base.ts
Required for https://github.com/NativeScript/nativescript-cli/issues/1247
> Use a temporary copy of built-in adb

- commands/preuninstall.ts
- package.json
- static-config-base.ts
See https://github.com/NativeScript/nativescript-cli/issues/1247
> Don't stop adb uninstall

- definitions/mobile.d.ts
- mobile/ios/ios-emulator-services.ts
- services/usb-livesync-service-base.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1210
> Remove files from iOS simulator

- declarations.d.ts
- file-system.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1285
> Enumerate empty directories

- mobile/ios/ios-core.ts
FIxes https://github.com/NativeScript/nativescript-cli/issues/956
> Better error reporting for deploy on device

- services/usb-livesync-service-base.ts
This will resolve the problem with endless loop when the application has before-prepare hook that modifies some files from app folder.
> Skip files that are not changed from sync

- package.json
- static-config-base.ts
> Set executable bit of adb

- services/hooks-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/1337
> Allow hooks to selectively stop the CLI process

- mobile/android/android-emulator-services.ts
On some devices ro.product.manufacturer returns unknown. This leads to endless loop for CLI.
Since the underlying emulation engine for Genymotion is VirtualBox and that's not going to change any time soon, I've added a check for ro.build.product property.
> Fix geny 2.6 emulator

- services/usb-livesync-service-base.ts
Allow for calling out to compilers in hooks and collecting changed files
afterwards.
Allow changes to excluded files (*.ts) to trigger a sync, and filter
those files out after the platform is prepared.
Fix livesync file filter bug on ios.
> (livesync) Wait for filesystem changes after prepare hook.

- README.md
- appbuilder/proton-bootstrap.ts
- definitions/mobile.d.ts
- mobile/android/android-device.ts
- mobile/ios/ios-device.ts
- package.json
For each device we can add isTablet property that will be true when we detect the device is Tablet.
Could be used to show different images in the UI.
> Add isTablet property for deviceInfo

- README.md
- definitions/mobile.d.ts
- test/unit-tests/appbuilder/device-log-provider.ts
Add information about `IDeviceInfo` interface and its properties.
Improve `README.md` with latest information of the Public API.
> Improve device documentation

- bootstrap.ts
- declarations.d.ts
- progress-indicator.ts
See https://github.com/NativeScript/nativescript-cli/issues/1294
> Share Progress indicator between the CLIs

- definitions/mobile.d.ts
- mobile/ios/device/ios-device.ts
- mobile/mobile-core/ios-device-discovery.ts
Fixes https://github.com/NativeScript/nativescript-cli/issues/1362
> Fix crash when launching applications on iOS device in debug mode

- test/unit-tests/mobile/project-files-manager.ts
> Fix unit tests on Windows

- config-base.ts
- definitions/config.d.ts
- services/commands-service.ts
- services/hooks-service.ts
Introduce a way to disable hooks globally through a .json property only.
> Facilitate disable hooks mechanism

- commands/device/list-devices.ts
Add new column - Status.
The values in it will be "Connected" when the device is reachable and "Unreachable" in case it is locked, not trusted, etc.
> Show device status when listing available devices

- mobile/ios/simulator/ios-simulator-application-manager.ts
When using `tns run ios` and `tns livesync ios` for iOS Simulator, we exit the process immediately instead of printing device logs.
Call the printDeviceLogs method from iOSSimPortable that will fix the issue.
> Print iOS Simulator device logs

- services/livesync-service-base.ts
During the last refactoring we've lost the queue of futures. So we had some racing issues when the same file is saved multiple times.
Fix this by adding back the queue and adding some try-catch statements.
> Fix ENOENT, EISDIR, EEXIST errors in livesync

- services/livesync-service-base.ts
Fix livesync of TypeScript projects - make sure gaze does not trigger any livesync logic in case the file that's changed is excluded via any pattern from livesync data.
Currently when .ts file is change, gaze detects changes for .ts, .js and .js.map files and fails as only .js files exist in platforms dir.
> Fix livesync of TypeScript projects

- declarations.d.ts
- file-system.ts
So that it can use a custom-set algorithm and encoding
In addition, add some interfaces, describing what Apple's Content Delivery API returns
> Extend fs' `getFileShasum`

- declarations.d.ts
- file-system.ts
Starting with "rm"
Required for http://teampulse.telerik.com/view#item/309474
> Integrate shelljs into IFileSystem

- README.md
- appbuilder/declarations.d.ts
- package.json
Update README.md with information for latest public API.
Update package.json for 0.5.0 relaese.
> Update README with information for latest public API

- services/commands-service.ts
Fix http://teampulse.telerik.com/view#item/292768
> Fix the autocomplete

- mobile/mobile-core/devices-service.ts
When CLI is trying to work with different devices, calling setInterval to detect new devices, while deploying/livesyncing on currently attached iOS device is throwing error 21 on MacOS.
For example: `appbuilder deploy` when only iOS device is attached.
Workaround this by detecting the platform first and call setInterval only in very rare cases.
> Workaround error 21 when working with iOS devices

- declarations.d.ts
- options.ts
Add list plugins registered in package.json file when executing tns plugin in project.
Add plugin find command to list the nativescript plugins available in npm. The command has --all and --count flags to change the output format.
> Add list dependencies

- appbuilder/providers/device-app-data-provider.ts
Use correct LiveSync urls for Companion apps
Fixes http://teampulse.telerik.com/view#item/313027
> Fix LiveSync to Companion apps

- package.json
> Set version to 0.6.0

- appbuilder/device-emitter.ts
- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/application-manager-base.ts
- mobile/constants.ts
- mobile/ios/device/ios-application-manager.ts
- mobile/ios/device/ios-core.ts
- mobile/ios/device/ios-proxy-services.ts
- mobile/ios/simulator/ios-simulator-application-manager.ts
- mobile/mobile-core/devices-service.ts
Add public API for checking if LiveSync is enabled.
Implement correct parsing of results when trying to get data from iOS devices as it comes on chunks.
> Add public API for checking is LiveSync enabled

- mobile/android/android-emulator-services.ts
After updating the Android default emulator the CLI starts it and cannot deploy the application on it. This is caused by the change in the OK message after the net.connect(port) client connects to the emulator.
Fixes https://github.com/NativeScript/nativescript-cli/issues/1689
> Fix new Android emulator fail to start application

- commands/post-install.ts
- definitions/config.d.ts
Add successfully installed message on post install. Show it only when the property in static config is set.
> Add successfully installed message on post install

- README.md
- package.json
- services/xcode-select-service.ts
- test/unit-tests/xcode-select-service.ts
Use sysInfoBase as it's the only one registered in common lib.
> Fix iOS Device detection 

- declarations.d.ts
- services/user-settings-service.ts
So that this base class can be extended by the AppBuilder CLI's classes
> Implement the full IUserSettingsService instead of UserSettings.IUserSettingsService

- README.md
- package.json
> Set version to 0.9.1

- verify-node-version.ts
Add warning that we'll drop support for node 0.10.x
> Deprecate node 0.10.x

- README.md
The public methods added to devicesService should be described in README.md.
> Add public methods to README.md

- definitions/mobile.d.ts
- mobile/mobile-core/android-device-discovery.ts
- mobile/mobile-core/android-process-service.ts
- mobile/mobile-core/devices-service.ts
Remove Xillium and use Safari's webinspector for iOS and Chrome's inspector for Android.
> Remove the old Mac debugger

- mobile/constants.ts
- services/livesync-service-base.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/1773
> Exclude explicitly changes in App_Resources folder and warn the user.

- appbuilder/project/project-base.ts
- mobile/android/android-application-manager.ts
- mobile/constants.ts
Do not use $projectConstants in AndroidApplicationManager as it's not available in {N}.
> Do not use $projectConstants as it's not available in {N}

- services/livesync-service-base.ts
When using `appbuilder livesync platform --watch` the name of the file that is synced is not displayed.
> Print currently livesynced file name

- README.md
- definitions/mobile.d.ts
- mobile/mobile-core/android-process-service.ts
- mobile/mobile-core/devices-service.ts
In the information for the debuggable application is included the framework - Cordova or NativeScript.
If the application is Cordova the content of the title tag in the currently opened html file in the android WebView is set as title of the application.
> Return more information for the debuggable android apps

- services/project-files-manager.ts
> Fix .js.map entries

- services/livesync-service-base.ts
When the livesync command is executed we do not need to log info for each file that is transfered. The information should be displayed when the --watch flag is set and some file is changed.
> Do not display all files when livesync is executed

- declarations.d.ts
- services/xcode-select-service.ts
- sys-info-base.ts
- test/unit-tests/xcode-select-service.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/1732
> Separate methods introduced for SysInfoBase

- appbuilder/services/livesync/livesync-service.ts
Check if file exists before executing LiveSync operation and throw correct error in case any of the file that should be synced is missing.
> Throw correct error during LiveSync if file does not exist

- README.md
- mobile/mobile-core/android-device-discovery.ts
- package.json
Prevent Future resolved more than once error when checking for new Android devices.
> Prevent Future resolved more than once error

- mobile/android/android-device-hash-service.ts
https://github.com/NativeScript/nativescript-cli/issues/1810
> Fixed: tns livesync android --emulator --watch fails when create new folder

- appbuilder/declarations.d.ts
- appbuilder/project/project-base.ts
- appbuilder/project/project.ts
- appbuilder/proton-bootstrap.ts
- appbuilder/providers/device-app-data-provider.ts
- appbuilder/services/livesync/companion-apps-service.ts
- appbuilder/services/livesync/ios-livesync-service.ts
- appbuilder/services/livesync/livesync-service.ts
- constants.ts
- declarations.d.ts
- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/android/android-device-file-system.ts
- mobile/android/android-device.ts
- mobile/application-manager-base.ts
- mobile/ios/device/ios-application-manager.ts
- mobile/ios/device/ios-device-file-system.ts
- mobile/ios/device/ios-device.ts
- mobile/ios/simulator/ios-simulator-application-manager.ts
- mobile/ios/simulator/ios-simulator-device.ts
- mobile/mobile-core/android-process-service.ts
- mobile/mobile-core/devices-service.ts
- options.ts
- services/livesync-service-base.ts
- services/project-files-manager.ts
- services/project-files-provider-base.ts
- test/unit-tests/mobile/devices-service.ts
- test/unit-tests/mobile/project-files-manager.ts
- test/unit-tests/project-files-provider-base.ts
Includes changes for
* Prop set/print commands
* Build
* LiveSync (both regular and companion)
TP Reference: [Support environment configurations](http://teampulse.telerik.com/view#item/308175)
Ping @rosen-vladimirov @TsvetanMilanov 
Tests are on the way!
> Implement configuration logic 

- appbuilder/project/project-base.ts
They can later be used in determining what to write in configuration files.
Ping @rosen-vladimirov, @TsvetanMilanov
> Store keys of configuration specific properties

- mobile/mobile-core/devices-service.ts
https://github.com/NativeScript/nativescript-cli/issues/1909
> Fixed: tns run android --emulator deploys to device

- commands/help.ts
- definitions/config.d.ts
Add Telerik AppBuilder CLI by progress line in the console help.
> Rebranding

- commands/doctor.ts
Change the info displayed for the warnings from the doctor command.
> Change info message in doctor command

- prompter.ts
One of our dependencies mute-stream has function pipe which calls the pipe of the Node js Stream and if the pipe is called with same destination multiple times the event listeners added to the stream will cause memory leak.
We need to check the event listeners of the process.stdout and clean them before we call pipe of MuteStream.
> Fix prompter memory leak

- services/livesync-service-base.ts
The array `localToDevicePaths` already contains all the filtered files which are relevant for performing LiveSync. Instead of copying the whole project folder, copy only those files.
> Copy only files which are relevant to LiveSync

- declarations.d.ts
- sys-info-base.ts
> Extract getNpmVersion as separate function

- mobile/mobile-core/android-process-service.ts
We need to clear the local ports which we use to debug Android applications after we receive the exit event of the process.
> Clear forwarded ports for Android on process exit

- bootstrap.ts
- declarations.d.ts
- helpers.ts
- mobile/android/logcat-helper.ts
- mobile/mobile-core/android-process-service.ts
- mobile/mobile-core/devices-service.ts
- services/process-service.ts
- test/unit-tests/mobile/devices-service.ts
- test/unit-tests/process-service.ts
We need to listen for SIGINT, SIGTERM and exit to kill the adb logcat process.
> Kill adb logcat process

- definitions/mobile.d.ts
- test/unit-tests/mobile/devices-service.ts
Add unit tests for the devices-service.
> Add tests for devices service

- services/typescript-service.ts
Previously there were some cases when TypeScript was unable to generate .js files. After adding the `noEmitOnError` parameter to tsconfig, TypeScript will not generate .js files ONLY when it is set to true.
Currently our TypeScriptService does not handle this case as it thinks that the .js files are not generated in some cases. Respect the parameter and always show the output of the compiler to the user.
> Support noEmitOnError parameter

- services/plugins/npm-plugins-service.ts
> Fix npm search core method

- mobile/android/android-emulator-services.ts
- mobile/wp8/wp8-emulator-services.ts
We need to check if the user has WP SDK installed to emulate on wp8 and if there are any emulators installed for android to emulate on android.
> Add checks for emulate on android and wp8

- services/typescript-service.ts
When we get the TS files data of the project we don't need the .d.ts files in the typeScriptFiles property.
Also when we add the TS files to tscommand.txt we need to add quotation marks to their names because some of them may contain spaces.
> Separate .d.ts files from .ts files.

- declarations.d.ts
Add platformSpecificLiveSyncServices to ILiveSyncProvider as it's required for NativeScript CLI.
> Add platformSpecificLiveSyncServices to ILiveSyncProvider

- appbuilder/services/npm-service.ts
Fix registry URL as it contains two slashes which causes code 500 of the http request.
> Fix registry url

- services/hooks-service.ts
Since we can have hooks with arguments which are invalid for the AppBuilder CLI (for example the before-livesync hook of nativescript-angular and watch hook of nativescript-dev-typescript) we need to check if the arguments of the hook are valid before we execute it. We can do the check only for hooks which can be executed in our process.
Fixes http://teampulse.telerik.com/view#item/321923
> Validate hook arguments before execute

- appbuilder/services/livesync/ios-livesync-service.ts
- constants.ts
- definitions/mobile.d.ts
- mobile/ios/device/ios-device-file-system.ts
- mobile/ios/device/ios-proxy-services.ts
- test/unit-tests/mobile/project-files-manager.ts
Old PR: https://github.com/telerik/mobile-cli-lib/pull/820
> LiveSync to /Documents

- appbuilder/appbuilder-bootstrap.ts
Change the path to ios-log-filter to point to the correct folder.
> Fix cannot find module ios-log-filter

- README.md
- appbuilder/services/npm-service.ts
- package.json
Merge release proton in master
> Merge release proton in master

- mobile/ios/device/ios-core.ts
Fix iOS operations when xml protocol is used. Due to changes in the Node API we are using, all iOS related operations which use XML protocol, started failing.
Use correct way to parse the result.
> Fix iOS operations

- mobile/mobile-core/android-process-service.ts
- test/unit-tests/yok.ts
Adds error handling where necessary, because shelljs is now throwing errors by default.
related to: https://github.com/NativeScript/nativescript-cli/pull/2364
> added error handling on shelljs operations where necessary

- helpers.ts
- test/unit-tests/helpers.ts
Add settlePromises method that will execute all promises instead of failing when the first promise is rejected. It will be used to replace `Future.wait(futures)`.
The method returns new promise that will be resolved when all promises are resolved. In case any of them is rejected, after all promises are completed, the returned promise will be rejected with an error, describing all errors during the execution.
> Add settlePromises method

- services/cancellation.ts
CLI uses special file ("cli") in the TEMP in order to detect when the process should be killed in cases a new installation is in progress.
However it looks like Nodejs chmodSync sometimes fails on Windows with ENOENT error.
As the chmod operation is required only for UNIX and Linux based OSes, do not try to execute it on Windows.
> Fix problem with non-existent cli file

- mobile/ios/device/ios-device-file-system.ts
Sometimes when executing the following command there is an error:
`node_modules/.bin/tns run ios --path TNS_App --teamId W7TGC3P93K --justlaunch`
`Error: There are outstanding futures. Construction call stacks:
#1
at IOSDeviceFileSystem.getFile (/Users/vchimev/Work/git/nativescript-cli-tests/node_modules/nativescript/lib/common/mobile/ios/device/ios-device-file-system.js:43:22)
at e (/Users/vchimev/Work/git/nativescript-cli-tests/node_modules/nativescript/lib/services/platform-service.js:655:35)
at Function.settle (/Users/vchimev/Work/git/nativescript-cli-tests/node_modules/fibers/future.js:249:26)
at FiberFuture.wait (/Users/vchimev/Work/git/nativescript-cli-tests/node_modules/fibers/future.js:565:10)
at PlatformLiveSyncServiceBase.shouldTransferAllFiles …
> Fixed: outstanding futures when getting files from iOS device

- services/livesync-service-base.ts
Fix await in livesync service base
> Fix await in livesync service base

- declarations.d.ts
- options.ts
Releated to https://github.com/NativeScript/nativescript-cli/pull/2440
> Remove getPort flag

- commands/device/put-file.ts
- declarations.d.ts
- definitions/mobile.d.ts
- mobile/android/android-device-file-system.ts
- mobile/ios/device/ios-device-file-system.ts
- mobile/ios/simulator/ios-simulator-file-system.ts
- options.ts
- services/cancellation.ts
- verify-node-version.ts
> Merge release in master

- decorators.ts
- test/unit-tests/decorators.ts
- test/unit-tests/mobile/devices-service.ts
- test/unit-tests/mocks/decorators-cache.ts
- test/unit-tests/mocks/decorators-invoke-before.ts
Add unit tests for:
* cache decorator
* invokeBefore decorator
* devicesService detectCurrentlyAttachedDevices method
> Add unit tests for decorators and devicesServices

- mobile/android/android-device.ts
- mobile/mobile-core/android-device-discovery.ts
- test/unit-tests/mobile/android-device-discovery.ts
Fix working with Android devices:
- incorrect error is raise when adb writes multiple times to stderr.
Instead of handling all errors when the process exists, we've rejected
the promise on the first write to stderr flag. Add unit-test for this.
- An error is raised during construction of AndroidDevice object when
the device is not authorized. In this case we should not throw error -
just set the status to Unreachable. The caller of AndroidDevice must
handle the case when the status is Unreachable.
- Fix case when some adb messages are reported as AndroidDevices, for
example `* daemon started successfully *`. Filter such messages in the
androidDeviceDiscovery. Add unit tests for such known messages.
> Fix working with android devices in some cases

- appbuilder/services/npm-service.ts
- declarations.d.ts
- services/livesync-service-base.ts
- services/process-service.ts
- services/typescript-service.ts
> Merge release-appbuilder into master

- child-process.ts
> Correct pipe name when emitting in spawnFromEvent

- bootstrap.ts
made alias for `tns device` command. Now it also works with `devices`.
> added alias for device command

- mobile/android/android-debug-bridge-result-handler.ts
_Problem_
Provide a better message when the device is connected but not paired:
_Solution_
Message is more verbose. Add suggestion for the user.
related issue: https://github.com/NativeScript/nativescript-cli/issues/1882#issuecomment-288433597
> provide a better message

- services/credentials-service.ts
Trace the error instead of throwing an exception.
> Fix proxy clear error on non Windows OS

- bootstrap.ts
- declarations.d.ts
- definitions/config.d.ts
- package.json
- services/qr.ts
- static-config-base.ts
This is needed by fusion as we need to display QR codes there
> Introduce QR service

- logger.ts
- test/unit-tests/logger.ts
TP Reference: [Obfuscate certificate passwords in file logs](http://teampulse.telerik.com/view#item/330690)
> Enhance regex to obfuscate passwords

- declarations.d.ts
- file-system.ts
> Introduce utimes to fs

- bootstrap.ts
- declarations.d.ts
- definitions/config.d.ts
- http-client.ts
- services/settings-service.ts
- static-config-base.ts
Currently only the user agent is configurable.
P.S. I'm open to suggestions regarding the name of the service
> Expose service for configuration

- declarations.d.ts
- file-system.ts
- mobile/mobile-core/devices-service.ts
- test/unit-tests/mobile/devices-service.ts
Merge release and release-appbuilder in master
> Merge release and release-appbuilder in master

- mobile/android/android-emulator-services.ts
Fix the errors for not found device to be consistent everywhere.
> Fix error messages to be consistent.

- services/typescript-service.ts
In case the project has `typescript` as a dependency use it for transpilation in lieu of our own.
> Transpile with project's tsc

- declarations.d.ts
- file-system.ts
> Add realpath method to fs

- README.md
> Fix npmService README

- definitions/mobile.d.ts
- mobile/ios/device/ios-device-operations.ts
- mobile/ios/device/ios-device.ts
Check if device identifier matches and emit only if it does.
> Fix deviceLogs emitted for all attached ios devices

- services/analytics-service-base.ts
> Protect $staticConfig

- services/html-help-service.ts
Placing `<span>` tags in CLI's markdown files will work when generating HTML help pages, but the tags will also be shown in terminal. Skip the tags when generating command-line help.
> Add support for `<span>` tag in CLI's help

- mobile/ios/simulator/ios-simulator-application-manager.ts
We need to set PID to the currently installed application in order to get a log.
https://github.com/NativeScript/nativescript-cli/pull/3079
> Always set application pid.

- options.ts
Ping @KristianDD @rosen-vladimirov
> Make bundle option string

- declarations.d.ts
Describes error that has stderr information.
needed for https://github.com/NativeScript/nativescript-cloud/pull/78
> Add IStdError

- services/dynamic-help-service.ts
Relates to: https://github.com/NativeScript/docs/issues/157 and https://github.com/NativeScript/nativescript-cli/pull/3357
> docs: new variable that is always false in the CLI

- declarations.d.ts
- sys-info-base.ts
Support brew version of Cocoapods
Fixes https://github.com/NativeScript/nativescript-cli/issues/3276
> feat(doctor): Support xcodeproj from brew

- commands/post-install.ts
- declarations.d.ts
- package.json
- progress-indicator.ts
Should be merged after:
https://github.com/NativeScript/nativescript-doctor/pull/28
https://github.com/NativeScript/nativescript-cli/pull/3418
> Getting started improvements

- helpers.ts
based on branch: `kddimitrov/nsconfig-app-folder`
update for helper methods necessary in the CLI
related PR: https://github.com/NativeScript/nativescript-cli/pull/3398
> refactor: update helpers

- helpers.ts
move plugin name resolution to common
> refactor: update helper methods

- declarations.d.ts
- test/unit-tests/yok.ts
- yok.ts
> chore: Merge release in master

- declarations.d.ts
- host-info.ts
- test/unit-tests/host-info.ts
- verify-node-version.ts
Add new method to get the macOS version. Also change the verifyNodeVersion implementation, so the messages that are created there, can be used by Sidekick.
> feat: Add method for getting macOS version

- .travis.yml
- helpers.ts
checkout https://github.com/NativeScript/nativescript-cli/pull/3745
> fix: remove the method ignoring AAR and include.gradle files from the livesync

- mobile/ios/simulator/ios-emulator-services.ts
Add support for --timeout option that can be passed to debug command.
Fix help of debug command.
> Increase the default timeout for debug command from 5 to 10 seconds

- mobile/mobile-core/devices-service.ts
Steps to reproduce:
1. Attach  android device
2. Detach  android device
An unhandled promise rejection error will be thrown.
> Fix unhandled promise rejection from sidekick

- helpers.ts
- test/unit-tests/helpers.ts
Fix settle promises to return the results in the correct order.
> Fix settle promises

- mobile/android/android-virtual-device-service.ts
Sometimes `tns devices` command hangs up on windows because net.connect is executed twice and does not return any data. This PR fixes this behaviour.
Sometimes net.connect throws  `ECONNREFUSED` error. In this case {N} CLI throws an unhandled error because of missing `.error` handler.  This PR adds a missing error handler.
In case when {N} CLI is not able to get imagerIdentifier of android emulator it will fallback to displayName from properties file.
> Fix android emulators

- mobile/android/android-virtual-device-service.ts
Clear correctly net connection to android's emulator port. In some cases `tns devices` command hangs up because net connection is not properly destroyed.
> Destroy properly net connection to android's emulator port

- test/unit-tests/mobile/android/logcat-helper.ts
Some logcat related tests fail, particularly the `should not kill the process if started with keepSingleProcess`. We are not sure what causes the issue, but we suspect it is related to the static variable that is used in the tests.
Replace it with a variable that is per instance.
> fix: logcat tests sometimes fail

- definitions/mobile.d.ts
- mobile/android/android-application-manager.ts
- mobile/android/logcat-helper.ts
- mobile/mobile-core/devices-service.ts
- test/unit-tests/android-application-manager.ts
- test/unit-tests/stubs.ts
Related to https://github.com/NativeScript/nativescript-cli/pull/3120
> Fix deploy on device to work with string and object identifiers.
